RomStart                 equ $00000000
RomHeaderOffset          equ $00000100
EntryPointOffset         equ $00000200
RomEndInclusive          equ $000BFFFF
VBlankTaskSlotCount_Immediate  equ $0004
VBlankTaskSlotCount_RoundRobin equ $0010
VBlankTaskSlotStride           equ $0080
VBlankTaskStateOffset          equ $0000
VBlankTaskStateActiveBit       equ $0080
ImmediateTaskCursorLimit       equ $0084
VBlankTimedDispatchFlagBit     equ $0006
VBlankTimedDispatchTickLimit   equ $0010
VBlankDispatchBudgetReset      equ $0010
VBlankTaskUserDataOffset       equ $0004
VBlankTaskCallbackOffset       equ $000C
VBlankTaskDelayOffset          equ $0040
VBlankTaskScriptPointerOffset  equ $0044
TaskAdvanceDelayTicks          equ $0E10
TaskAdvanceReadyFlagBit        equ $0004
TaskScriptProgressReadyBit     equ $0007
SecondaryTaskReadyBit          equ $0007
SecondaryTaskStatusSlot0       equ -$80
SecondaryTaskStatusSlot1       equ -$7F
InventoryMenuVisibleRowCount   equ $0004
InventoryMenuEntryDisplayWidth equ $000E
InventoryMenuBlinkDelayTicks   equ $0014
InventoryMenuBlinkEnabledBit   equ $0000
InventoryMenuBlinkVisibleBit   equ $0001
InventoryMenuVisibleEntryIdMask equ $0007
InventoryMenuVisibleEntryMarkedBit equ $0080
InventoryMenuBlankTile         equ $8020
InventoryMenuNormalEntryTileBase equ $8000
InventoryMenuSelectedEntryTileBase equ $A000
InventoryMenuScrollUpTile      equ $8013
InventoryMenuScrollDownTile    equ $9013
InventoryMenuCursorTile        equ $87B5
InventoryMenuHeadingCoordsWide equ $1004
InventoryMenuHeadingCoordsNarrow equ $0B04
InventoryMenuVisibleEntrySelectedBit equ $0007
HudDigitTileBase              equ $8030
DecimalDisplayClampMax        equ $000F423F
InventoryMenuLevelMarkerTile  equ $8017
MagicMenuStatusLayoutLockedBit equ $0004
MagicMenuStatusSelectionSlotCount equ $000C
MagicMenuEntryGridColumnCount equ $0003
MagicSpellCount               equ $0006
MagicMenuSpellBarRowCount     equ $0002
MagicMenuTopRowSlotLastIndex  equ $0001
MagicMenuSixChoiceLastDirectionIndex equ $0003
MagicMenuSpellPageStateSelector equ $0005
MagicMenuStatusValueBias      equ $0008
InventoryMenuPauseSentinelEntryId equ $0007
InventoryMenuBlinkPhaseTicks  equ $000C
InventoryMenuBlinkEffectTicks equ $0050
InventoryMenuAnyActionPressedMask equ $00F0
VBlankMenuTextTransferRequestMask equ $0004
MagicMenuSubmodeExitPressedMask equ $0060
MagicMenuStatusGaugeSegmentCount equ $0003
MagicMenuStatusGaugeHeightRows equ $0003
MagicMenuStatusGaugeTileRowWidth equ $0008
MagicMenuStatusGaugeMaxWidth equ $0010
MagicMenuStatusGaugeHalfClampValue equ $0200
MagicMenuStatusGaugeClampValue equ $0400
MagicMenuStatusGaugeAnimationTicks equ $00C0
MagicMenuStatusGaugeScaleBundleStride equ $000A
MagicMenuStatusGaugePageShift equ $0008
MagicMenuStatusGaugeAlternatePageShift equ $0005
MagicMenuStatusGaugeSelectionValueOffset equ $000A
MagicMenuStatusGaugeMaxFillValue equ $000C
MagicMenuStatusGaugePageSelectionCutoff equ $0008
MagicMenuStatusTopRowSelectionCutoff equ $0008
