; ======================================================================
; ram_addresses.asm
; RAM address definitions for Wonder Boy in Monster World (Genesis)
; Work RAM is mapped at $FF0000-$FFFFFF on the 68K bus.
; Symbols are auto-named RAM_<type>_<hex>; hand-named ones are traced.
; ======================================================================

; ============================================================
; $00xxxx work RAM
; ============================================================
RAM_ScriptScratch                 = $00FF1400 ; script interpreter scratch (0x400 longs)
RAM_word_00FF2400                 = $00FF2400
RAM_word_00FF2600                 = $00FF2600
RAM_word_00FF2800                 = $00FF2800
RAM_TileStagingBuffer             = $00FF2D00 ; tile decode staging buffer (0x800 bytes)
RAM_word_00FF3300                 = $00FF3300
RAM_word_00FF5000                 = $00FF5000
RAM_PaletteSource                 = $00FF8B56 ; palette source (display layout), 128 bytes
RAM_PaletteWorking                = $00FF8BD6 ; palette working, uploaded to CRAM
RAM_word_00FFF600                 = $00FFF600
; ============================================================
; $FFxxxx work RAM
; ============================================================
RAM_ObjectRAM                     = $FF0C00 ; object RAM block base (index * $40)
RAM_long_FF3100                   = $FF3100
RAM_long_FF3300                   = $FF3300
RAM_word_FF5000                   = $FF5000
RAM_word_FFFF8000                 = $FFFF8000
RAM_word_FFFF8002                 = $FFFF8002
RAM_VBlankFlag                    = $FFFF8006 ; VBlank flag (bit 0 set in VBlank)
RAM_word_FFFF8054                 = $FFFF8054
RAM_word_FFFF8068                 = $FFFF8068
RAM_word_FFFF80C8                 = $FFFF80C8
RAM_SchedulerCursor               = $FFFF8A48 ; task scheduler cursor / active flag
RAM_VBlankTick                    = $FFFF8A49 ; VBlank frame counter
RAM_word_FFFF8A4A                 = $FFFF8A4A
RAM_word_FFFF8A4B                 = $FFFF8A4B
RAM_CurrentTaskSlot               = $FFFF8A4C ; current task slot pointer
RAM_word_FFFF8A4E                 = $FFFF8A4E
RAM_word_FFFF8A4F                 = $FFFF8A4F
RAM_word_FFFF8A50                 = $FFFF8A50
RAM_word_FFFF8A51                 = $FFFF8A51
RAM_RNGState                      = $FFFF8A52 ; RNG LCG state (seed $2A6D365A)
RAM_word_FFFF8A56                 = $FFFF8A56
RAM_word_FFFF8A5A                 = $FFFF8A5A
RAM_word_FFFF8A5C                 = $FFFF8A5C
RAM_word_FFFF8A5D                 = $FFFF8A5D
RAM_word_FFFF8A5E                 = $FFFF8A5E
RAM_word_FFFF8A5F                 = $FFFF8A5F
RAM_word_FFFF8A60                 = $FFFF8A60
RAM_PlaneA_Addr                   = $FFFF8A62 ; Plane A VRAM address
RAM_SpriteTable_Addr              = $FFFF8A64 ; sprite attribute table VRAM address
RAM_PlaneB_Addr                   = $FFFF8A66 ; Plane B VRAM address
RAM_SpriteDims_Addr               = $FFFF8A68 ; sprite dimensions VRAM address
RAM_BgColor_Addr                  = $FFFF8A6A ; background colour VRAM address
RAM_word_FFFF8A6C                 = $FFFF8A6C
RAM_word_FFFF8A6D                 = $FFFF8A6D
RAM_word_FFFF8A6E                 = $FFFF8A6E
RAM_word_FFFF8A6F                 = $FFFF8A6F
RAM_ScrollY                       = $FFFF8A70 ; scroll offset Y (pixels)
RAM_ScrollX                       = $FFFF8A72 ; scroll offset X (pixels)
RAM_word_FFFF8A74                 = $FFFF8A74
RAM_word_FFFF8A76                 = $FFFF8A76
RAM_word_FFFF8A77                 = $FFFF8A77
RAM_InputSelected                 = $FFFF8A7A ; selected-input mirror (current)
RAM_InputSelectedPrev             = $FFFF8A7B ; selected-input mirror (previous)
RAM_InputSelectedNew              = $FFFF8A7C ; selected-input mirror (new press)
RAM_InputSelected2                = $FFFF8A7D ; second selected-input mirror byte
RAM_word_FFFF8A7E                 = $FFFF8A7E
RAM_P1Pad                         = $FFFF8A7F ; P1 pad triplet base (current/prev/new)
RAM_word_FFFF8A80                 = $FFFF8A80
RAM_word_FFFF8A81                 = $FFFF8A81
RAM_P2Pad                         = $FFFF8A82 ; P2 pad triplet base (current/prev/new)
RAM_word_FFFF8A83                 = $FFFF8A83
RAM_word_FFFF8A84                 = $FFFF8A84
RAM_ScrollPixelX                  = $FFFF8A86 ; scroll X pixel counter
RAM_ScrollPixelY                  = $FFFF8A88 ; scroll Y pixel counter
RAM_ScrollPlaneBase               = $FFFF8A8A ; scroll plane base nibble
RAM_word_FFFF8A8B                 = $FFFF8A8B
RAM_word_FFFF8ADC                 = $FFFF8ADC
RAM_word_FFFF8ADE                 = $FFFF8ADE
RAM_word_FFFF8AE0                 = $FFFF8AE0
RAM_word_FFFF8AE2                 = $FFFF8AE2
RAM_word_FFFF8AE4                 = $FFFF8AE4
RAM_word_FFFF8B28                 = $FFFF8B28
RAM_word_FFFF8B2A                 = $FFFF8B2A
RAM_word_FFFF8B2E                 = $FFFF8B2E
RAM_word_FFFF8B30                 = $FFFF8B30
RAM_word_FFFF8B31                 = $FFFF8B31
RAM_word_FFFF8B32                 = $FFFF8B32
RAM_word_FFFF8B33                 = $FFFF8B33
RAM_word_FFFF8B34                 = $FFFF8B34
RAM_word_FFFF8B36                 = $FFFF8B36
RAM_word_FFFF8B38                 = $FFFF8B38
RAM_word_FFFF8B3A                 = $FFFF8B3A
RAM_word_FFFF8B50                 = $FFFF8B50
RAM_word_FFFF8B52                 = $FFFF8B52
RAM_word_FFFF8C56                 = $FFFF8C56
RAM_word_FFFF8C57                 = $FFFF8C57
RAM_word_FFFF8C6E                 = $FFFF8C6E
RAM_word_FFFF8C6F                 = $FFFF8C6F
RAM_word_FFFF8C70                 = $FFFF8C70
RAM_word_FFFF8C71                 = $FFFF8C71
RAM_word_FFFF8C72                 = $FFFF8C72
RAM_word_FFFF8C73                 = $FFFF8C73
RAM_word_FFFF8C74                 = $FFFF8C74
RAM_word_FFFF8C76                 = $FFFF8C76
RAM_SceneDataPtr                  = $FFFF8C7A ; current scene data pointer
RAM_CellX                         = $FFFF8C9A ; current map cell X (screen units)
RAM_CellY                         = $FFFF8C9C ; current map cell Y (screen units)
RAM_SceneWidth                    = $FFFF8C9E ; scene width (screen cells)
RAM_SceneHeight                   = $FFFF8CA0 ; scene height (screen cells)
RAM_SceneEventCounter             = $FFFF8CA2 ; scene event loop counter
RAM_word_FFFF8CA3                 = $FFFF8CA3
RAM_PlayerState                   = $FFFF8CA4 ; player state byte
RAM_PlayerSubState                = $FFFF8CA5 ; player sub-state byte
RAM_PlayerStateValue              = $FFFF8CA6 ; player state value
RAM_SceneScriptPtr                = $FFFF8CA8 ; scene-event script pointer
RAM_TransitionTimer               = $FFFF8CAA ; scene transition timer
RAM_TransitionValue               = $FFFF8CAB ; scene transition value
RAM_word_FFFF8CAC                 = $FFFF8CAC
RAM_word_FFFF8CAD                 = $FFFF8CAD
RAM_word_FFFF8CAE                 = $FFFF8CAE
RAM_word_FFFF8CAF                 = $FFFF8CAF
RAM_word_FFFF8CB0                 = $FFFF8CB0
RAM_word_FFFF8CB2                 = $FFFF8CB2
RAM_word_FFFF8CB4                 = $FFFF8CB4
RAM_EventFlag                     = $FFFF8CC2 ; scene event flag byte
RAM_EventCounter                  = $FFFF8CC3 ; scene event counter
RAM_word_FFFF8CC4                 = $FFFF8CC4
RAM_word_FFFF8CC5                 = $FFFF8CC5
RAM_word_FFFF8CD2                 = $FFFF8CD2
RAM_word_FFFF8CD3                 = $FFFF8CD3
RAM_word_FFFF8CD4                 = $FFFF8CD4
RAM_word_FFFF8CD6                 = $FFFF8CD6
RAM_PlayerEnterHandler            = $FFFF8CDA ; per-scene enter-handler pointer
RAM_word_FFFF8CDE                 = $FFFF8CDE
RAM_word_FFFF8D10                 = $FFFF8D10
RAM_SceneOriginX                  = $FFFF8D92 ; scene X origin
RAM_SceneOriginY                  = $FFFF8D94 ; scene Y origin
RAM_ScreenTilesX                  = $FFFF8D96 ; screen size X (tiles)
RAM_ScreenTilesY                  = $FFFF8D98 ; screen size Y (tiles)
RAM_ScrollOffsetX                 = $FFFF8D9A ; current scroll offset X (tiles)
RAM_ScrollOffsetY                 = $FFFF8D9C ; current scroll offset Y (tiles)
RAM_RenderMode                    = $FFFF8D9E ; tilemap render mode
RAM_RenderRows                    = $FFFF8DA0 ; tilemap render rows
RAM_RenderCols                    = $FFFF8DA2 ; tilemap render cols
RAM_RenderRowSkip                 = $FFFF8DA4 ; tilemap render row skip
RAM_RenderColSkip                 = $FFFF8DA6 ; tilemap render col skip
RAM_word_FFFF950A                 = $FFFF950A
RAM_word_FFFF959C                 = $FFFF959C
RAM_word_FFFF95BE                 = $FFFF95BE
RAM_word_FFFF95BF                 = $FFFF95BF
RAM_word_FFFF95C0                 = $FFFF95C0
RAM_word_FFFF95C1                 = $FFFF95C1
RAM_word_FFFF95C2                 = $FFFF95C2
RAM_word_FFFF95D7                 = $FFFF95D7
RAM_word_FFFF95D8                 = $FFFF95D8
RAM_word_FFFF95D9                 = $FFFF95D9
RAM_word_FFFF95FA                 = $FFFF95FA
RAM_word_FFFF9606                 = $FFFF9606
RAM_word_FFFF9610                 = $FFFF9610
RAM_word_FFFF9612                 = $FFFF9612
RAM_word_FFFF9614                 = $FFFF9614
RAM_word_FFFF9615                 = $FFFF9615
RAM_word_FFFF9616                 = $FFFF9616
RAM_word_FFFF9618                 = $FFFF9618
RAM_word_FFFF961A                 = $FFFF961A
RAM_word_FFFF961B                 = $FFFF961B
RAM_word_FFFF961C                 = $FFFF961C
RAM_word_FFFF961E                 = $FFFF961E
RAM_word_FFFF9620                 = $FFFF9620
RAM_word_FFFF9621                 = $FFFF9621
RAM_word_FFFF9622                 = $FFFF9622
RAM_word_FFFF9623                 = $FFFF9623
RAM_word_FFFF9624                 = $FFFF9624
RAM_word_FFFF9625                 = $FFFF9625
RAM_word_FFFF9626                 = $FFFF9626
RAM_word_FFFF9627                 = $FFFF9627
RAM_HUD_HP                        = $FFFF9628 ; HUD HP mirror
RAM_HUD_Gold                      = $FFFF962A ; HUD gold mirror
RAM_word_FFFF962C                 = $FFFF962C
RAM_word_FFFF9634                 = $FFFF9634
RAM_word_FFFF9658                 = $FFFF9658
RAM_word_FFFF9659                 = $FFFF9659
RAM_word_FFFF965A                 = $FFFF965A
RAM_word_FFFF965C                 = $FFFF965C
RAM_word_FFFF965E                 = $FFFF965E
RAM_word_FFFF965F                 = $FFFF965F
RAM_word_FFFF9661                 = $FFFF9661
RAM_word_FFFF9662                 = $FFFF9662
RAM_word_FFFF9667                 = $FFFF9667
RAM_word_FFFF9668                 = $FFFF9668
RAM_word_FFFF966A                 = $FFFF966A
RAM_word_FFFF966B                 = $FFFF966B
RAM_word_FFFF9676                 = $FFFF9676
RAM_word_FFFF9678                 = $FFFF9678
RAM_word_FFFF967A                 = $FFFF967A
RAM_word_FFFF967C                 = $FFFF967C
RAM_word_FFFF968A                 = $FFFF968A
RAM_word_FFFF974C                 = $FFFF974C
RAM_word_FFFF974E                 = $FFFF974E
RAM_word_FFFF9750                 = $FFFF9750
RAM_word_FFFF9752                 = $FFFF9752
RAM_PlayerX                       = $FFFF9758 ; player world X
RAM_PlayerY                       = $FFFF975A ; player world Y
RAM_word_FFFF975C                 = $FFFF975C
RAM_word_FFFF975E                 = $FFFF975E
RAM_word_FFFF9778                 = $FFFF9778
RAM_word_FFFF9798                 = $FFFF9798
RAM_word_FFFF979A                 = $FFFF979A
RAM_word_FFFF980E                 = $FFFF980E
RAM_word_FFFF980F                 = $FFFF980F
RAM_word_FFFF9854                 = $FFFF9854
RAM_word_FFFF9855                 = $FFFF9855
RAM_word_FFFF9856                 = $FFFF9856
RAM_word_FFFF985A                 = $FFFF985A
RAM_word_FFFF9962                 = $FFFF9962
RAM_word_FFFF9966                 = $FFFF9966
RAM_word_FFFF9968                 = $FFFF9968
RAM_word_FFFF996A                 = $FFFF996A
RAM_word_FFFF996C                 = $FFFF996C
RAM_word_FFFF9974                 = $FFFF9974
RAM_word_FFFF9976                 = $FFFF9976
RAM_word_FFFF9978                 = $FFFF9978
RAM_word_FFFF997A                 = $FFFF997A
RAM_word_FFFF9980                 = $FFFF9980
RAM_word_FFFF9981                 = $FFFF9981
RAM_word_FFFF9982                 = $FFFF9982
RAM_word_FFFF9984                 = $FFFF9984
RAM_word_FFFF9986                 = $FFFF9986
RAM_word_FFFF998A                 = $FFFF998A
RAM_word_FFFF9994                 = $FFFF9994
RAM_word_FFFF9995                 = $FFFF9995
RAM_word_FFFF99DE                 = $FFFF99DE
RAM_word_FFFF99E4                 = $FFFF99E4
RAM_word_FFFF99E6                 = $FFFF99E6
RAM_word_FFFF99EA                 = $FFFF99EA
RAM_word_FFFF99EE                 = $FFFF99EE
RAM_word_FFFF99F0                 = $FFFF99F0
RAM_word_FFFF99F2                 = $FFFF99F2
RAM_word_FFFF99F4                 = $FFFF99F4
RAM_word_FFFF9A8A                 = $FFFF9A8A
RAM_word_FFFF9A8B                 = $FFFF9A8B
RAM_word_FFFF9A8C                 = $FFFF9A8C
RAM_word_FFFF9A8E                 = $FFFF9A8E
RAM_word_FFFF9A94                 = $FFFF9A94
RAM_word_FFFF9BB6                 = $FFFF9BB6
RAM_word_FFFF9BB7                 = $FFFF9BB7
RAM_word_FFFF9BB8                 = $FFFF9BB8
RAM_word_FFFF9BB9                 = $FFFF9BB9
RAM_word_FFFF9BBA                 = $FFFF9BBA
RAM_word_FFFF9BBE                 = $FFFF9BBE
RAM_word_FFFF9BC0                 = $FFFF9BC0
RAM_word_FFFF9BC2                 = $FFFF9BC2
RAM_word_FFFF9BC4                 = $FFFF9BC4
RAM_word_FFFF9BC6                 = $FFFF9BC6
RAM_word_FFFF9BC8                 = $FFFF9BC8
RAM_word_FFFF9BCA                 = $FFFF9BCA
RAM_word_FFFF9BCC                 = $FFFF9BCC
RAM_word_FFFF9BD6                 = $FFFF9BD6
RAM_word_FFFF9BD8                 = $FFFF9BD8
RAM_word_FFFF9BF3                 = $FFFF9BF3
RAM_word_FFFF9C14                 = $FFFF9C14
RAM_word_FFFF9C16                 = $FFFF9C16
RAM_word_FFFF9C18                 = $FFFF9C18
RAM_word_FFFF9C1C                 = $FFFF9C1C
RAM_word_FFFF9C20                 = $FFFF9C20
RAM_word_FFFF9C22                 = $FFFF9C22
RAM_word_FFFF9ED4                 = $FFFF9ED4
RAM_word_FFFF9ED6                 = $FFFF9ED6
RAM_word_FFFF9EDA                 = $FFFF9EDA
RAM_word_FFFF9EDB                 = $FFFF9EDB
RAM_word_FFFF9EDC                 = $FFFF9EDC
RAM_word_FFFF9EDE                 = $FFFF9EDE
RAM_word_FFFF9EE0                 = $FFFF9EE0
RAM_word_FFFF9EE2                 = $FFFF9EE2
RAM_word_FFFF9EE4                 = $FFFF9EE4
RAM_word_FFFF9EE6                 = $FFFF9EE6
RAM_word_FFFF9EE8                 = $FFFF9EE8
RAM_word_FFFF9EEE                 = $FFFF9EEE
RAM_word_FFFF9EF1                 = $FFFF9EF1
RAM_word_FFFF9EF2                 = $FFFF9EF2
RAM_word_FFFF9EF6                 = $FFFF9EF6
RAM_word_FFFF9EFA                 = $FFFF9EFA
RAM_word_FFFF9EFC                 = $FFFF9EFC
RAM_word_FFFF9EFE                 = $FFFF9EFE
RAM_word_FFFF9F00                 = $FFFF9F00
RAM_word_FFFF9F02                 = $FFFF9F02
RAM_word_FFFF9F03                 = $FFFF9F03
RAM_word_FFFF9F04                 = $FFFF9F04
RAM_word_FFFF9F05                 = $FFFF9F05
RAM_word_FFFF9F06                 = $FFFF9F06
RAM_word_FFFF9F07                 = $FFFF9F07
RAM_word_FFFF9F08                 = $FFFF9F08
RAM_word_FFFF9F09                 = $FFFF9F09
RAM_word_FFFF9F0A                 = $FFFF9F0A
RAM_word_FFFF9F0B                 = $FFFF9F0B
RAM_word_FFFF9F0D                 = $FFFF9F0D
RAM_word_FFFF9F0F                 = $FFFF9F0F
RAM_word_FFFF9F13                 = $FFFF9F13
RAM_word_FFFF9F14                 = $FFFF9F14
RAM_word_FFFF9F16                 = $FFFF9F16
RAM_word_FFFF9F1E                 = $FFFF9F1E
RAM_word_FFFF9F22                 = $FFFF9F22
RAM_word_FFFF9F26                 = $FFFF9F26
RAM_word_FFFF9F32                 = $FFFF9F32
RAM_word_FFFFA11A                 = $FFFFA11A
RAM_word_FFFFA11C                 = $FFFFA11C
RAM_word_FFFFA142                 = $FFFFA142
RAM_word_FFFFA148                 = $FFFFA148
RAM_word_FFFFA14A                 = $FFFFA14A
RAM_word_FFFFA394                 = $FFFFA394
RAM_word_FFFFA396                 = $FFFFA396
RAM_word_FFFFA398                 = $FFFFA398
RAM_word_FFFFA39A                 = $FFFFA39A
RAM_word_FFFFA3A4                 = $FFFFA3A4
RAM_word_FFFFC008                 = $FFFFC008

; ============================================================
; Entity object layout (A4 = entity slot base, $FFC000 for slot 0)
; Offsets are negative A4-relative. Absolute = $FFC000 + offset.
; ============================================================
ENT_AttackRange             = -$2100 ; attack range ($FF9F00)
ENT_Defense                 = -$2300 ; defense bits ($FF9D00)
ENT_Gold                    = -$2600 ; gold ($FF9A00)
ENT_Attack                  = -$2700 ; attack value ($FF9900)
ENT_StateVal                = -$3000 ; movement state value ($FF9000)
ENT_State                   = -$3100 ; movement state bits ($FF8F00)
ENT_MaxVelX                 = -$3300 ; max velocity X ($FF8D00)
ENT_AccelX                  = -$3400 ; acceleration X ($FF8C00)
ENT_ColW                    = -$3500 ; collision width ($FF8B00)
ENT_VelX                    = -$3600 ; velocity X ($FF8A00)
ENT_Y                       = -$3700 ; world Y ($FF8900)
ENT_X                       = -$3800 ; world X ($FF8800)
ENT_Repeat                  = -$3900 ; script repeat count ($FF8700)
ENT_Flags                   = -$4000 ; active/flags byte ($FF8000)
ENT_Counter                 = -$3FFE ; counter/flags word ($FF8002)
ENT_ScriptFlag              = -$3FFD ; script flags ($FF8003)
ENT_DataPtr                 = -$3F00 ; data pointer ($FF8100)
ENT_TreeIdx0                = -$3D00 ; script tree index 0 ($FF8300)
ENT_TreeIdx1                = -$3CFF ; script tree index 1 ($FF8301)
ENT_TreeIdx2                = -$3CFE ; script tree index 2 ($FF8302)
ENT_StreamPtr               = -$3C00 ; script stream pointer ($FF8400)
ENT_BasePtr                 = -$3B00 ; script base pointer ($FF8500)
ENT_Counter2                = -$3A00 ; script counter ($FF8600)
ENT_Decrement               = -$39FE ; script counter decrement ($FF8602)
ENT_Countdown               = -$38FF ; script countdown ($FF8701)
ENT_XSub                    = -$37FE ; world X subpixel ($FF8802)
ENT_YSub                    = -$36FE ; world Y subpixel ($FF8902)
ENT_VelY                    = -$35FE ; velocity Y ($FF8A02)
ENT_VelYSub                 = -$35FD ; velocity Y subpixel ($FF8A03)
ENT_ColH                    = -$34FF ; collision height ($FF8B01)
ENT_ColW2                   = -$34FE ; collision width 2 ($FF8B02)
ENT_ColH2                   = -$34FD ; collision height 2 ($FF8B03)
ENT_MaxVelY                 = -$32FE ; max velocity Y ($FF8D02)
ENT_ColFlags                = -$2F00 ; collision flags ($FF9100)
ENT_PrevX                   = -$2E00 ; previous X ($FF9200)
ENT_PrevY                   = -$2DFE ; previous Y ($FF9202)
ENT_Object                  = -$2D00 ; linked object slot ($FF9300)
ENT_Step                    = -$2C00 ; script step counter ($FF9400)
ENT_Anim                    = -$2BFF ; animation id ($FF9401)
ENT_HPTimer                 = -$2BFE ; HP timer ($FF9402)
ENT_HP                      = -$2BFD ; current HP ($FF9403)
ENT_PlayerFlags             = -$2AFD ; player/entity flags ($FF9503)
ENT_StatIdx                 = -$26FE ; stat index ($FF9902)
ENT_Damage                  = -$23FE ; damage source ($FF9C02)
