SystemStackTop           equ $00FF0C00
WorkRamStart             equ $00FF0000
WorkRamEnd               equ $00FFFFFF
TaskScriptScratchBuffer   equ $00FF3300
VBlankDispatchFlags      equ $00FF8006
VBlankDispatchFlags_Short equ $FFFF8006
TaskCompletionResult      equ $00FF8068
TaskCompletionResult_Short equ $FFFF8068
ImmediateTaskSlots       equ $00FF8048
ImmediateTaskSlots_Short equ $FFFF8048
ImmediateTaskSlot0Callback equ $00FF8054
ImmediateTaskSlot0Callback_Short equ $FFFF8054
SecondaryTaskSlots       equ $00FF80C8
SecondaryTaskSlots_Short equ $FFFF80C8
RoundRobinTaskSlots      equ $00FF8248
RoundRobinTaskSlots_Short equ $FFFF8248
ImmediateTaskCursor      equ $00FF8A48
ImmediateTaskCursor_Short equ $FFFF8A48
VBlankTickCounter        equ $00FF8A49
VBlankTickCounter_Short  equ $FFFF8A49
RoundRobinTaskIndex      equ $00FF8A4A
RoundRobinTaskIndex_Short equ $FFFF8A4A
TaskDispatchBudget       equ $00FF8A4B
TaskDispatchBudget_Short equ $FFFF8A4B
CurrentTaskSlotPointer   equ $00FF8A4C
CurrentTaskSlotPointer_Short equ $FFFF8A4C
TaskScriptCountdown      equ $00FF8A4E
TaskScriptCountdown_Short equ $FFFF8A4E
TaskScriptValue          equ $00FF8A4F
TaskScriptValue_Short    equ $FFFF8A4F
TaskScriptMode           equ $00FF8A50
TaskScriptMode_Short     equ $FFFF8A50
SelectedInputPlaybackCountdown equ $00FF8A4E
SelectedInputPlaybackCountdown_Short equ $FFFF8A4E
SelectedInputPlaybackValue equ $00FF8A4F
SelectedInputPlaybackValue_Short equ $FFFF8A4F
SelectedInputPlaybackMode equ $00FF8A50
SelectedInputPlaybackMode_Short equ $FFFF8A50
TaskScriptFlags          equ $00FF8A51
TaskScriptFlags_Short    equ $FFFF8A51
TaskScriptStateLong      equ $00FF8A52
TaskScriptStateLong_Short equ $FFFF8A52
TaskScriptProgressCurrent equ $00FF8A7A
TaskScriptProgressCurrent_Short equ $FFFF8A7A
TaskScriptProgressPrevious equ $00FF8A7B
TaskScriptProgressPrevious_Short equ $FFFF8A7B
TaskScriptProgressFlags  equ $00FF8A7C
TaskScriptProgressFlags_Short equ $FFFF8A7C
SecondaryTaskStatusSelector equ $00FF8A7D
SecondaryTaskStatusSelector_Short equ $FFFF8A7D
SelectedInputCurrent     equ $00FF8A7A
SelectedInputCurrent_Short equ $FFFF8A7A
SelectedInputPrevious    equ $00FF8A7B
SelectedInputPrevious_Short equ $FFFF8A7B
SelectedInputPressed     equ $00FF8A7C
SelectedInputPressed_Short equ $FFFF8A7C
SelectedInputSource      equ $00FF8A7D
SelectedInputSource_Short equ $FFFF8A7D
; `0x8A7A-0x8A7D` is still shared between the task/bootstrap path and live pad input.
; Current best fit: the task/bootstrap path reuses this quartet as the selected-input
; playback mirror, while `0x8A4E-0x8A50` holds the packed duration/value state loaded
; from `TaskScriptProgressBuffer`.
Player1InputCurrent      equ $00FF8A7F
Player1InputCurrent_Short equ $FFFF8A7F
Player1InputPrevious     equ $00FF8A80
Player1InputPrevious_Short equ $FFFF8A80
SecondaryTaskReadySlot0   equ $00FF8A81
SecondaryTaskReadySlot0_Short equ $FFFF8A81
Player1InputPressed      equ $00FF8A81
Player1InputPressed_Short equ $FFFF8A81
Player2InputCurrent      equ $00FF8A82
Player2InputCurrent_Short equ $FFFF8A82
Player2InputPrevious     equ $00FF8A83
Player2InputPrevious_Short equ $FFFF8A83
SecondaryTaskReadySlot1   equ $00FF8A84
SecondaryTaskReadySlot1_Short equ $FFFF8A84
Player2InputPressed      equ $00FF8A84
Player2InputPressed_Short equ $FFFF8A84
BootstrapPatchSlot0      equ $00FF8B34
BootstrapPatchSlot0_Short equ $FFFF8B34
BootstrapPatchSlot1      equ $00FF8B36
BootstrapPatchSlot1_Short equ $FFFF8B36
BootstrapPatchSlot2      equ $00FF8B38
BootstrapPatchSlot2_Short equ $FFFF8B38
BootstrapPatchSlot3      equ $00FF8B3A
BootstrapPatchSlot3_Short equ $FFFF8B3A
TaskDispatchTimingFlags  equ $00FF8A5D
TaskDispatchTimingFlags_Short equ $FFFF8A5D
TaskAdvanceReadyFlags    equ $00FF8C56
TaskAdvanceReadyFlags_Short equ $FFFF8C56
TaskScriptAuxFlag        equ $00FF9658
TaskScriptAuxFlag_Short  equ $FFFF9658
TaskScriptProgressBuffer equ $00FF1400
AsyncTaskReadyByte       equ $00FFA3A4
AsyncTaskReadyByte_Short equ $FFFFA3A4
TaskScriptAuxScratchBuffer equ $00FF9996
TaskScriptAuxScratchBuffer_Short equ $FFFF9996
