; ======================================================================
; wonderboy.asm — top-level build entry.
; Includes the shared constants/vectors (header.asm) and the
; auto-generated data_rest.asm which in turn includes each disassembled
; region module in ascending ROM-address order.
; Assembles to a bit-perfect reproduction of game.rom.
; ======================================================================

	include "header.asm"

; Build orchestrator + all region modules + raw gaps ($200-$C0000).
; AUTO-GENERATED by tools/regen_rest.js from tools/regions.json. Do not edit.
	include "data_rest.asm"
