#!/usr/bin/env node
// dump2dcb.js — emit ROM bytes [start,end) as dc.b into an output file.
// Usage: node tools/dump2dcb.js <rom> <out> <start> <end> [bytes_per_line]
const fs = require('fs');

const [, , romPath, outPath, startArg, endArg, bplArg] = process.argv;
if (!romPath || !outPath || !startArg || !endArg) {
  console.error('Usage: dump2dcb.js <rom> <out> <start> <end> [bytes_per_line]');
  process.exit(1);
}

const rom = fs.readFileSync(romPath);
const start = parseInt(startArg, 16);
const end = parseInt(endArg, 16);
const bpl = bplArg ? parseInt(bplArg, 10) : 16;

let lines = [];
lines.push('; ======================================================================');
lines.push('; data_rest.asm — raw ROM bytes $' + start.toString(16).toUpperCase() +
           '-$' + end.toString(16).toUpperCase());
lines.push('; Generated by tools/dump2dcb.js. Replace with real code as disassembled.');
lines.push('; ======================================================================');
let hex = [];
for (let i = start; i < end; i++) {
  hex.push('$' + rom[i].toString(16).padStart(2, '0'));
}
let lines_ = [];
for (let i = 0; i < hex.length; i += bpl) {
  lines_.push('\tdc.b\t' + hex.slice(i, i + bpl).join(', '));
}
lines = lines.concat(lines_);
fs.writeFileSync(outPath, lines.join('\n') + '\n');
console.error('Wrote ' + (end - start) + ' bytes to ' + outPath + ' (' + lines_.length + ' lines)');