#!/usr/bin/env node
// regen_dialogue.js — regenerate the scene data + scene table region in
// src/data/main_data.asm from the editable text in text/scenes.json.
//
// Unmodified scenes keep their original bytes (bit-perfect). Edited scenes are
// re-encoded with greedy dictionary compression, then all scenes are repacked
// sequentially (from the original first-scene address) and the scene table
// offsets rebuilt. Run build.sh afterwards.
//
// USAGE: node regen_dialogue.js [--check]

const fs = require('fs');
const rom = fs.readFileSync('game.rom');
const words = [];
let wi = 0x22027;
for (let n = 0; n < 168; n++) {
  const e = rom.indexOf(0, wi);
  if (e < 0 || e - wi > 30) break;
  words.push(rom.slice(wi, e).toString('ascii'));
  wi = e + 1;
}
function encodeText(text) {
  const bytes = [];
  let i = 0;
  while (i < text.length) {
    const ch = text[i];
    if (ch === '\n') { bytes.push(0x09); i++; continue; }
    if (ch === '…') { bytes.push(0x02); i++; continue; }
    let best = -1, bestLen = 0;
    for (let w = 0; w < words.length; w++) {
      const word = words[w];
      if (word && text.startsWith(word, i) && word.length > bestLen) { best = w; bestLen = word.length; }
    }
    if (best >= 0 && bestLen >= 3) { bytes.push(0x0C, best < 0x40 ? best : best + 0x40); i += bestLen; continue; }
    const code = text.charCodeAt(i);
    if (code >= 0x20 && code < 0x7F) { bytes.push(code); i++; continue; }
    bytes.push(0x20); i++;
  }
  return bytes;
}

const scenes = JSON.parse(fs.readFileSync('text/scenes.json', 'utf8'));
const SCENE_TABLE = 0x1DD94;
let changedAny = false;
for (const sc of scenes) {
  let bytes = [];
  for (const seg of sc.segments) {
    if (seg.type === 'text') {
      if (seg.text === seg.origText) bytes = bytes.concat(seg.raw); // unchanged -> keep original bytes
      else bytes = bytes.concat(encodeText(seg.text));               // edited -> re-encode
    } else {
      bytes = bytes.concat(seg.raw);
    }
  }
  let orig = [];
  for (const seg of sc.segments) orig = orig.concat(seg.raw);
  const same = orig.length === bytes.length && orig.every((b, k) => b === bytes[k]);
  if (!same) { changedAny = true; console.log('scene', sc.index, 'changed:', orig.length, '->', bytes.length); }
  sc._bytes = same ? orig : bytes;
}
if (!changedAny) {
  // no edits: emit the exact original ROM bytes for the region (bit-perfect)
  const regionStart = 0x1DD74;
  const REGION_END = 0x20D50;
  const region = rom.slice(regionStart, REGION_END);
  const out = [];
  out.push('; ======================================================================');
  out.push('; src/data/scene_data.asm');
  out.push('; Scene type table + scene table + dialogue script data');
  out.push('; AUTO-GENERATED by tools/regen_dialogue.js from text/scenes.json');
  out.push('; Covers ROM $001DD74-$20D50.');
  out.push('; ======================================================================');
  for (let a2 = regionStart; a2 < REGION_END; a2 += 16) {
    const n = Math.min(16, REGION_END - a2);
    const bytes = [];
    for (let k = 0; k < n; k++) bytes.push('$' + region[a2 - regionStart + k].toString(16).padStart(2, '0'));
    out.push('\tdc.b\t' + bytes.join(',') + '\t; $' + a2.toString(16).toUpperCase());
  }
  fs.writeFileSync('src/data/scene_data.asm', out.join('\n') + '\n');
  console.log('regenerated src/data/scene_data.asm (original, bit-perfect)');
  process.exit(0);
}
// relayout scenes sequentially from the original first-scene address
const base = scenes[0].dataAddr;
let cursor = base;
const layout = [];
for (const sc of scenes) {
  layout.push({ index: sc.index, addr: cursor, bytes: sc._bytes });
  cursor += sc._bytes.length;
}
const totalBytes = cursor - base;
const REGION_END = 0x20D50;
console.log('scene data region:', base.toString(16), '-', cursor.toString(16), '(' + totalBytes + ' bytes, limit', (REGION_END - base) + ')');
if (cursor > REGION_END) { console.log('ERROR: scenes overflow by', cursor - REGION_END, 'bytes; shorten edited text'); process.exit(1); }
// rebuild the region bytes: type table ($1DD74-$1DD93), scene table ($1DD94), data
const regionStart = 0x1DD74;
const region = Buffer.alloc(REGION_END - regionStart);
rom.copy(region, 0, regionStart, 0x1DD94); // type table (32 bytes) unchanged
let off = 0x1DD94 - regionStart;
for (const sc of scenes) {
  const rel = layout.find(l => l.index === sc.index).addr - SCENE_TABLE;
  region[off] = sc.type;
  region[off + 1] = (rel >> 8) & 0xFF;
  region[off + 2] = rel & 0xFF;
  off += 3;
}
for (const l of layout) Buffer.from(l.bytes).copy(region, l.addr - regionStart);
// write src/data/scene_data.asm
const file = 'src/data/scene_data.asm';
const out2 = [];
out2.push('; ======================================================================');
out2.push('; src/data/scene_data.asm');
out2.push('; Scene type table + scene table + dialogue script data');
out2.push('; AUTO-GENERATED by tools/regen_dialogue.js from text/scenes.json');
out2.push('; Covers ROM $001DD74-$20D50.');
out2.push('; ======================================================================');
for (let a2 = regionStart; a2 < REGION_END; a2 += 16) {
  const n = Math.min(16, REGION_END - a2);
  const bytes = [];
  for (let k = 0; k < n; k++) bytes.push('$' + region[a2 - regionStart + k].toString(16).padStart(2, '0'));
  out2.push('\tdc.b\t' + bytes.join(',') + '\t; $' + a2.toString(16).toUpperCase());
}
fs.writeFileSync(file, out2.join('\n') + '\n');
console.log('regenerated', file);
console.log('run ./build.sh to assemble');
