#!/usr/bin/env node
// regen_assets.js — regenerate labeled data modules from the editable assets.
//   src/tile_blocks.asm    <- assets/tiles.png  (+ assets/tile_blocks.json)
//   src/palette_table.asm  <- assets/palettes.json
// Round-trip with extract_assets.js is bit-perfect: an unmodified asset set
// reproduces the exact ROM bytes. Edited tiles/palettes (same count, same
// 4bpp/17-byte formats) are re-encoded here, so build.sh + verify.sh pick
// them up with no pointer changes.
//
// USAGE: node tools/regen_assets.js

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const DIR = path.resolve(__dirname, '..');
const rom = fs.readFileSync(path.join(DIR, 'game.rom'));
const A = (p) => path.join(DIR, 'assets', p);

// ---------------- tile decode/encode (shared with extract/inject) ----------------
function decodeTile(rom, off) {
  const px = new Uint8Array(64);
  for (let y = 0; y < 8; y++) for (let p = 0; p < 4; p++) {
    const byte = rom[off + y * 4 + p];
    for (let x = 0; x < 8; x++) if ((byte >> (7 - x)) & 1) px[y * 8 + x] |= 1 << p;
  }
  return px;
}
function encodeTile(indices) {
  const out = Buffer.alloc(32);
  for (let y = 0; y < 8; y++) for (let p = 0; p < 4; p++) {
    let byte = 0;
    for (let x = 0; x < 8; x++) { const idx = indices[y * 8 + x]; if (idx > 15) throw new Error('pixel index > 15'); if (idx & (1 << p)) byte |= 1 << (7 - x); }
    out[y * 4 + p] = byte;
  }
  return out;
}
function parsePNG(path) {
  const b = fs.readFileSync(path);
  let off = 8, w = 0, h = 0, bpp = 0, colorType = 0, idat = [];
  while (off < b.length) {
    const len = b.readUInt32BE(off);
    const type = b.toString('ascii', off + 4, off + 8);
    const data = b.slice(off + 8, off + 8 + len);
    if (type === 'IHDR') { w = data.readUInt32BE(0); h = data.readUInt32BE(4); colorType = data[9]; }
    else if (type === 'IDAT') idat.push(data);
    off += 12 + len;
  }
  const rawpx = zlib.inflateSync(Buffer.concat(idat));
  bpp = colorType === 3 ? 1 : colorType === 2 ? 3 : colorType === 6 ? 4 : 1;
  const stride = w * bpp;
  const out = Buffer.alloc(stride * h);
  let prev = Buffer.alloc(stride);
  for (let y = 0; y < h; y++) {
    const f = rawpx[y * (stride + 1)];
    const row = rawpx.slice(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    const cur = out.slice(y * stride, (y + 1) * stride);
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? cur[x - bpp] : 0, bv = prev[x], c = x >= bpp ? prev[x - bpp] : 0;
      let v = row[x];
      if (f === 1) v = (v + a) & 0xff;
      else if (f === 2) v = (v + bv) & 0xff;
      else if (f === 3) v = (v + ((a + bv) >> 1)) & 0xff;
      else if (f === 4) { const p = a + bv - c; const pa = Math.abs(p - a), pb = Math.abs(p - bv), pc = Math.abs(p - c); v = (v + (pa <= pb && pa <= pc ? a : pb <= pc ? bv : c)) & 0xff; }
      cur[x] = v;
    }
    prev = cur;
  }
  return { w, h, bpp, pix: out };
}
// ---------------- generate tile block modules (one per contiguous group) ----------------
{
  const blocks = JSON.parse(fs.readFileSync(A('tile_blocks.json'), 'utf8')).addresses.map(a => parseInt(a, 16));
  const img = parsePNG(A('tiles.png'));
  const TILE_STRIDE = 38, TILE_BYTES = 32;
  if (img.w !== TILE_STRIDE * 8 || img.h !== blocks.length * 8) {
    throw new Error('tiles.png size ' + img.w + 'x' + img.h + ' != expected ' + TILE_STRIDE * 8 + 'x' + blocks.length * 8);
  }
  // group contiguous blocks
  const groups = [];
  for (let i = 0; i < blocks.length; i++) {
    if (i === 0 || blocks[i] !== blocks[i - 1] + TILE_STRIDE * TILE_BYTES) groups.push([]);
    groups[groups.length - 1].push(blocks[i]);
  }
  groups.forEach((gb, gi) => {
    const rows = [];
    rows.push('; ======================================================================');
    rows.push('; src/tile_blocks_' + gi + '.asm — AUTO-GENERATED by tools/regen_assets.js');
    rows.push('; ' + gb.length + ' x 38-tile block(s) (tag $01 flagged-table records), 4bpp planar.');
    rows.push('; Source: assets/tiles.png. Bit-exact when unmodified.');
    rows.push('; ======================================================================');
    gb.forEach((addr, bi) => {
      const globalBi = groups.slice(0, gi).reduce((a, g) => a + g.length, 0) + bi;
      rows.push('TileBlock_' + gi + '_' + bi + ':\t\t; $' + addr.toString(16).toUpperCase());
      for (let t = 0; t < TILE_STRIDE; t++) {
        const indices = new Array(64);
        for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) indices[y * 8 + x] = img.pix[(globalBi * 8 + y) * img.w + t * 8 + x];
        const tile = encodeTile(indices);
        const hex = [...tile].map(b => '$' + b.toString(16).padStart(2, '0')).join(',');
        rows.push('\tdc.b\t' + hex + '\t; tile ' + t + ' @ $' + (addr + t * TILE_BYTES).toString(16).toUpperCase());
      }
      rows.push('');
    });
    fs.writeFileSync(path.join(DIR, 'src/tile_blocks_' + gi + '.asm'), rows.join('\n'));
    console.log('wrote src/tile_blocks_' + gi + '.asm (' + gb.length + ' blocks, $' + gb[0].toString(16) + '-$' + (gb[gb.length - 1] + TILE_STRIDE * TILE_BYTES).toString(16) + ')');
  });
}
// ---------------- generate palette_table.asm ----------------
{
  const palettes = JSON.parse(fs.readFileSync(A('palettes.json'), 'utf8'));
  const rows = [];
  rows.push('; ======================================================================');
  rows.push('; src/palette_table.asm — AUTO-GENERATED by tools/regen_assets.js');
  rows.push('; 252 x 17-byte packed palettes (LoadPalettes/DecodePalette format).');
  rows.push('; Source: assets/palettes.json. Bit-exact when unmodified.');
  rows.push('; ======================================================================');
  rows.push('PaletteTable:');
  for (const p of palettes) {
    const colors = p.colors.map(c => parseInt(c, 16));
    const field = new Array(15).fill(0);
    const bytes = [];
    for (let c = 1; c < 16; c++) {
      const w = colors[c];
      bytes.push(((w >> 1) & 7) | (((w >> 5) & 7) << 3) | (((w >> 9) & 3) << 6));
      if ((w >> 11) & 1) field[c - 1] = 1;
    }
    let f = 0;
    for (let c = 0; c < 15; c++) if (field[c]) f |= 1 << c;
    // preserve unused field bit 15 (byte0 bit7) from the extracted raw field
    const raw = p.field || [0, 0];
    const b0 = ((f >> 8) & 0x7F) | (raw[0] & 0x80);
    const b1 = f & 0xff;
    rows.push('Palette_' + p.index + ':');
    rows.push('\tdc.b\t$' + b0.toString(16).padStart(2, '0') + ',$' + b1.toString(16).padStart(2, '0') + '\t; $' + (0x599C + p.index * 17).toString(16).toUpperCase() + ' (blue-high field)');
    for (let c = 0; c < 15; c += 8) {
      const n = Math.min(8, 15 - c);
      rows.push('\tdc.b\t' + bytes.slice(c, c + n).map(b => '$' + b.toString(16).padStart(2, '0')).join(','));
    }
  }
  fs.writeFileSync(path.join(DIR, 'src/palette_table.asm'), rows.join('\n'));
  console.log('wrote src/palette_table.asm (' + palettes.length + ' palettes)');
}
