#!/usr/bin/env node
// regen_rest.js — regenerate data_rest.asm from the ROM.
// data_rest.asm is the build orchestrator for everything at/after $200:
// it `include`s each disassembled region module (in ascending-address order,
// from tools/regions.json) and emits the un-disassembled gaps as dc.b.
// The top-level source only needs: include the raw vectors/header + data_rest.asm.
//
// Usage: node tools/regen_rest.js <rom>
const fs = require('fs');

const [, , romPath] = process.argv;
if (!romPath) { console.error('Usage: regen_rest.js <rom>'); process.exit(1); }

const ROM = fs.readFileSync(romPath);
const ROMEND = ROM.length;
const MANIFEST = './tools/regions.json';
const OUT = './data_rest.asm';

const regions = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'))
  .map(r => ({ file: r.file, start: parseInt(r.start, 16), end: parseInt(r.end, 16) }))
  .sort((a, b) => a.start - b.start);

// validate no overlaps
for (let i = 0; i < regions.length; i++) {
  if (i && regions[i].start < regions[i - 1].end)
    throw new Error('regions.json overlap: ' + regions[i - 1].file + ' vs ' + regions[i].file);
}

const out = [];
out.push('; ======================================================================');
out.push('; data_rest.asm — build orchestrator + raw gaps, $200-$' + ROMEND.toString(16));
out.push('; AUTO-GENERATED by tools/regen_rest.js. Do not edit by hand;');
out.push('; used regions are tracked in tools/regions.json.');
out.push('; ======================================================================');

let a = 0x200;
let ri = 0;
while (a < ROMEND) {
  if (ri < regions.length && regions[ri].start === a) {
    out.push('');
    out.push('; --- ' + regions[ri].file + ' ($' + regions[ri].start.toString(16).toUpperCase() +
             '-$' + regions[ri].end.toString(16).toUpperCase() + ') ---');
    out.push('\tinclude "' + regions[ri].file + '"');
    a = regions[ri].end;
    ri++;
    continue;
  }
  // emit gap bytes
  const gapEnd = (ri < regions.length) ? regions[ri].start : ROMEND;
  let hex = [];
  while (a < gapEnd) { hex.push('$' + ROM[a].toString(16).padStart(2, '0')); a++; }
  for (let i = 0; i < hex.length; i += 16)
    out.push('\tdc.b\t' + hex.slice(i, i + 16).join(', '));
}

fs.writeFileSync(OUT, out.join('\n') + '\n');
console.error('regen_rest: wrote ' + OUT + ' (' + regions.length + ' region module(s), ROM $200-$' + ROMEND.toString(16) + ')');