const fs = require('fs');
const renames = {
  'loc_1424': 'ActionCancel',
  'loc_1434': 'ActionMenu',
  'loc_1448': 'ActionConfirm',
  'loc_1464': 'ActionUp',
  'loc_1474': 'ActionEnterDoor',
  'loc_149E': 'ActionEnterDoor_Store',
  'loc_14A4': 'ActionEnterDoor_Done',
  'loc_14A6': 'CheckPlayerActive',
  'loc_14BE': 'ClearPlayerActive',
  'loc_14C8': 'CheckSceneEvent',
  'loc_14E4': 'SceneEventDelay',
  'loc_14EC': 'SceneEventLoadPtr',
  'loc_150E': 'SceneEventReadVal',
  'loc_1524': 'SceneEventDrawMap',
  'loc_1546': 'SceneEventLoop',
  'loc_1550': 'SceneEventDispatch',
  'loc_1566': 'SceneEventReadSub',
  'loc_1568': 'SceneEventDispatch2',
  'loc_1596': 'SceneEventSavePtr',
  'loc_163A': 'SceneEventJump',
  'loc_168C': 'SceneEventSkip',
  'loc_1706': 'RenderFullScene_Cols',
  'loc_171C': 'RenderFullScene_Col',
  'loc_172C': 'RenderFullScene_Done',
  'loc_172E': 'SceneTransitionWait',
  'loc_173C': 'SceneTransitionEnd',
  'loc_174A': 'SceneTransitionWait_Done',
  'loc_174C': 'SceneTransitionSet',
  'loc_1774': 'SceneTransitionTick',
  'loc_1782': 'SceneTransitionFade',
  'loc_1790': 'SceneTransitionStart',
  'loc_1798': 'SceneTransitionFadeIn',
  'loc_179C': 'SceneTransitionRender',
  'loc_17BC': 'SceneTransitionRenderRow',
  'loc_17C2': 'SceneTransitionRender_Done',
  'loc_1814': 'SceneCmd_Text',
  'loc_183E': 'FormatNumber_Clear',
  'loc_1840': 'FormatNumber',
  'loc_1854': 'FormatNumber_Loop',
  'loc_187A': 'SceneCmd_Text2',
  'loc_1886': 'SceneCmd_RunScript',
  'loc_18A0': 'SceneCmd_Sprite',
  'loc_18FA': 'SceneCmd_ValueTable',
  'loc_19AC': 'SceneCmd_CheckFlag',
  'loc_19DE': 'SceneCmd_Subroutine',
  'loc_1A5E': 'RenderSceneRow',
  'loc_1A64': 'RenderSceneRow_Tile',
  'loc_1B1A': 'SceneCmd_Random',
  'loc_1B2A': 'SceneCmd_Random_Count',
  'loc_1B60': 'Div16_Loop',
  'loc_1BAA': 'SceneCmd_ItemCheck',
  'loc_1BB6': 'SceneCmd_ItemCheck_Next',
  'loc_1C0A': 'SceneCmd_AddGold',
  'loc_1C2C': 'SceneCmd_SkipData',
  'loc_1C38': 'SceneCmd_GoldCheck',
  'loc_1CA0': 'SceneCmd_RestoreStream',
  'loc_1CA2': 'SceneCmd_Resume',
  'loc_1CBC': 'CheckMenuInput',
  'loc_1CC8': 'CheckMenuInput2',
  'loc_1CD4': 'CheckMenuInput3',
  'loc_1CE0': 'MenuCountdown',
  'loc_1CF6': 'MenuItemCheck',
  'loc_1D1C': 'MenuItemCheck_Set',
  'loc_1D2C': 'MenuItemCheck_Confirm',
  'loc_1D50': 'RenderSceneRow2',
  'loc_1D56': 'RenderSceneRow2_Tile',
  'loc_1D70': 'MenuItemCheck_Done',
  'loc_1DA6': 'GetDictValue_Lookup',
  'loc_1E6A': 'QuizTextSetup',
  'loc_1E7C': 'QuizTextLoop',
  'loc_1E88': 'QuizTextBack',
  'loc_1E92': 'QuizTextControl',
  'loc_1E9C': 'QuizTextControl_Wait',
  'loc_1EB4': 'QuizTextChar',
  'loc_1EC4': 'QuizTextStore',
  'loc_1ED0': 'QuizTextDispatch',
  'loc_1EEC': 'BuildTextLine',
  'loc_1F26': 'BuildTextLine_Copy',
  'loc_1F36': 'BuildTextLine_Render2',
  'loc_1F46': 'FormatNumberLine',
  'loc_1F8E': 'CopyChars',
  'loc_1F90': 'CopyChars_Loop',
  'loc_1FA2': 'CopyChars_Store',
  'loc_1FAA': 'CopyChars_Done',
  'loc_1FAC': 'FillLine',
  'loc_1FBC': 'FillLine_Loop',
  'loc_1FD4': 'InitDialogue',
  'loc_20C0': 'RenderTilemapPlane_Col',
  'loc_20C4': 'RenderTilemapPlane_ColWait',
  'loc_20EE': 'RenderTilemapPlane_Col2',
  'loc_2194': 'UpdateScrollRegs_EntityLoop',
  'loc_21E0': 'UpdateScrollRegs_EntityNext',
  'loc_21F6': 'WriteScrollRegs_Tile',
};
let total = 0;
for (const f of fs.readdirSync('src').filter(x => x.endsWith('.asm'))) {
  let txt = fs.readFileSync('src/' + f, 'latin1');
  let before = txt;
  for (const [old, next] of Object.entries(renames)) {
    txt = txt.split(old).join(next);
  }
  if (txt !== before) { fs.writeFileSync('src/' + f, txt); total++; console.log(f); }
}
console.log('files touched:', total);
