const fs = require('fs');
const renames = {
  'loc_22D0': 'LoadTileBlock_WaitFree',
  'loc_22D8': 'LoadTileBlock_WaitReady',
  'loc_225E': 'RenderTilemapGridRow',
  'loc_2260': 'RenderTilemapGridCol',
  'loc_2292': 'RenderTilemapGrid_NextSlot',
  'loc_22A6': 'RenderTilemapGrid_Done',
  'loc_233C': 'LoadSceneTiles_Next',
  'loc_234C': 'DecodeStream',
  'loc_2356': 'DecodeStream_Control',
  'loc_236A': 'DecodeStream_Repeat',
  'loc_2370': 'DecodeStream_Run',
  'loc_2392': 'DecodeStream_Fill',
  'loc_23A4': 'DecodeStream_Done',
  'loc_23C6': 'TrapSpin_23C6',
  'loc_23CC': 'InstallObjectTask',
  'loc_23F8': 'CheckItemId',
  'loc_2408': 'CheckItemCount',
  'loc_2426': 'CheckItemCount_Done',
  'loc_242A': 'CheckItemType',
  'loc_243E': 'CheckItemType_Table',
  'loc_244A': 'CheckItemFlag',
  'loc_2452': 'CheckItemFlag_Set',
  'loc_2456': 'CheckItemFlag_Clear',
  'loc_247C': 'AddItem',
  'loc_2490': 'AddItem_Store',
  'loc_24B2': 'AddItem_Next',
  'loc_24BA': 'CheckItemMulti',
  'loc_24C4': 'CheckItemType2',
  'loc_24D2': 'SetItemFlag',
  'loc_24FE': 'RemoveItem',
  'loc_2502': 'RemoveItem_Sub',
  'loc_250A': 'ClearItemFlag',
  'loc_250E': 'ClearItemFlag_Done',
  'loc_2510': 'MapItemId',
  'loc_2520': 'MapItemId2',
  'loc_2532': 'MapItemId_Add',
  'loc_2536': 'ItemFlagAddr',
  'loc_2550': 'TilemapAddr_ClampX',
  'loc_255A': 'TilemapAddr_ClampY',
  'loc_2566': 'TilemapAddr_ClampY2',
  'loc_2570': 'TilemapAddr_Block',
  'loc_257E': 'TilemapAddr_Block2',
  'loc_258A': 'TilemapAddr_Block3',
  'loc_2594': 'TilemapAddr_Check',
  'loc_259E': 'TilemapAddr_Lookup',
  'loc_25C8': 'TilemapAddr_Done',
  'loc_260A': 'TilemapAddr2',
  'loc_2624': 'TilemapAddr2_Block',
  'loc_2630': 'TilemapAddr2_Block2',
  'loc_263A': 'TilemapAddr2_Lookup',
  'loc_2666': 'TilemapAddr_Write',
  'loc_2670': 'DrawTile',
  'loc_2690': 'DrawTile_Done',
  'loc_2694': 'DrawTile_ToVDP',
  'loc_26DA': 'DrawTile_Attr',
  'loc_270C': 'GetFlagBitAddr',
  'loc_2726': 'GetFlagBitAddr_Done',
  'loc_2738': 'GetMonsterFlagAddr',
  'loc_27F0': 'FindEntitySlot',
  'loc_27FE': 'EventListLoop',
  'loc_2804': 'EventListTile',
  'loc_282A': 'DrawTileRect',
  'loc_2834': 'DrawTileRect_Col',
  'loc_2870': 'DrawTileRect2',
  'loc_287A': 'DrawTileRect2_Col',
  'loc_28B0': 'EventAnimLoop',
  'loc_28CC': 'EventAnimCmd',
  'loc_28D8': 'EventAnimCtrl',
  'loc_28EE': 'EventAnimJump',
  'loc_28FA': 'EventAnimCtrl2',
  'loc_290C': 'EventAnimCtrl3',
  'loc_291E': 'EventAnimToggle',
  'loc_2926': 'EventAnimSet',
  'loc_293A': 'EventAnimDraw',
  'loc_2964': 'EventAnimStore',
  'loc_2968': 'EventAnimNext',
  'loc_2988': 'EventAnimInit',
  'loc_29BC': 'EventAreaLoop',
  'loc_29F4': 'EventAreaClear',
  'loc_29FA': 'EventAreaCheck',
  'loc_2A3C': 'EventAreaTrigger',
  'loc_2A40': 'EventAreaAdvance',
  'loc_2A58': 'EventAreaNext',
  'loc_2A60': 'EventAreaNext2',
  'loc_2A80': 'EventAreaInit',
  'loc_2AC4': 'DialogueWait',
  'loc_2ACE': 'DialoguePoll',
  'loc_2AE6': 'DialogueSelect',
  'loc_2AFA': 'DialogueSelect_Bad',
  'loc_2AFC': 'DialogueSelect_Return',
  'loc_2B08': 'DialogueChoice',
  'loc_2B28': 'DialogueChoice_Sound',
  'loc_2C20': 'PlayNoteAnim',
  'loc_2C2C': 'PlayNoteAnim_Note',
  'loc_2C56': 'SpawnNote',
  'loc_2CBE': 'SpawnNote_Done',
  'loc_2CC0': 'SpawnMusicNote',
  'loc_2D28': 'MonsterRage_Done',
  'loc_2D2A': 'MonsterRage',
  'loc_2D60': 'MonsterRage_Dx',
  'loc_2D76': 'MonsterRage_Dy',
  'loc_2D8C': 'MonsterRage_HitTest',
  'loc_2DB4': 'MonsterRage_Apply',
  'loc_2DCC': 'MonsterRage_Random',
  'loc_2DDA': 'MonsterRage_Store',
  'loc_2DDE': 'MonsterRage_Next',
  'loc_2DF2': 'MonsterRage_SetDelay',
  'loc_2E1C': 'MonsterRage_Init',
  'loc_2E8A': 'MonsterMove_A',
  'loc_2EEA': 'MonsterMove_B',
  'loc_2F28': 'MonsterMove_C',
  'loc_2F7E': 'MonsterMove_D',
};
let total = 0;
for (const f of fs.readdirSync('src').filter(x => x.endsWith('.asm'))) {
  let txt = fs.readFileSync('src/' + f, 'latin1');
  let before = txt;
  for (const [old, next] of Object.entries(renames)) {
    txt = txt.split(old).join(next);
  }
  if (txt !== before) { fs.writeFileSync('src/' + f, txt); total++; console.log(f); }
}
// remove empty leftover labels in the QuizTextData region
for (const f of fs.readdirSync('src').filter(x => x.endsWith('.asm'))) {
  let lines = fs.readFileSync('src/' + f, 'latin1').split(/\r?\n/);
  const empty = new Set(['loc_2BB8:', 'loc_2BC2:', 'loc_2BCC:', 'loc_2BE8:']);
  let changed = false;
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    if (empty.has(lines[i].trim())) { changed = true; continue; }
    out.push(lines[i]);
  }
  if (changed) fs.writeFileSync('src/' + f, out.join('\n'));
}
console.log('done');
