const fs = require('fs');
const renames = {
  'loc_A20': 'ClearEntityVelocity',
  'loc_A7E': 'SetEntityFlags_ClearBit4',
  'loc_A82': 'SetEntityFlags_Store',
  'loc_A86': 'SetEntityFlags_Next',
  'loc_AA8': 'ClearEntityFlags_Store',
  'loc_AAC': 'ClearEntityFlags_Next',
  'loc_AD6': 'IntegrateVelocityY',
  'loc_AF4': 'UpdateVelocityX',
  'loc_B06': 'UpdateVelocityX_Clamp',
  'loc_B20': 'UpdateVelocityX_Add',
  'loc_B28': 'UpdateVelocityX_Neg',
  'loc_B34': 'UpdateVelocityX_Check',
  'loc_B3A': 'UpdateVelocityX_Max',
  'loc_B3C': 'UpdateVelocityX_Store',
  'loc_B40': 'UpdateVelocityX_Done',
  'loc_B56': 'UpdateVelocityY_Clamp',
  'loc_B70': 'UpdateVelocityY_Add',
  'loc_B78': 'UpdateVelocityY_Neg',
  'loc_B84': 'UpdateVelocityY_Check',
  'loc_B8A': 'UpdateVelocityY_Max',
  'loc_B8C': 'UpdateVelocityY_Store',
  'loc_B90': 'UpdateVelocityY_Done',
  'loc_BA0': 'DecelerateVelocityX',
  'loc_BA4': 'DecelerateVelocityX_Zero',
  'loc_BA6': 'DecelerateVelocityX_Store',
  'loc_BAA': 'DecelerateVelocityX_Done',
  'loc_BBA': 'DecelerateVelocityY',
  'loc_BBE': 'DecelerateVelocityY_Zero',
  'loc_BC0': 'DecelerateVelocityY_Store',
  'loc_BC4': 'DecelerateVelocityY_Done',
  'loc_BC6': 'IsOnScreenX',
  'loc_BEA': 'IsOnScreenX_Visible',
  'loc_BF4': 'IsOnScreenY',
  'loc_C18': 'IsOnScreenY_Visible',
  'loc_C3E': 'CheckCollisionBoxes',
  'loc_C64': 'CheckCollisionBoxes_Loop',
  'loc_C84': 'CheckCollisionBoxes_Hit',
  'loc_C9A': 'CheckCollisionBoxes_NoHit',
  'loc_C9C': 'CheckCollisionBoxes_Clear',
  'loc_CA0': 'CheckBoxOverlap',
  'loc_CAE': 'CheckBoxOverlap_XNeg',
  'loc_CC2': 'CheckBoxOverlap_YNeg',
  'loc_CCE': 'CheckBoxOverlap_XTest',
  'loc_CF2': 'CheckBoxOverlap_YAdd',
  'loc_D04': 'CheckBoxOverlap_YNeg2',
  'loc_D10': 'CheckBoxOverlap_YTest',
  'loc_D22': 'CheckBoxOverlap_Done',
  'loc_D2C': 'CheckEntityCollision',
  'loc_D44': 'CheckEntityCollision_Loop',
  'loc_D52': 'CheckEntityCollision_Hit',
  'loc_D68': 'CheckEntityCollision_NoHit',
  'loc_D6A': 'CheckEntityCollision_Clear',
  'loc_D76': 'CheckObjectCollision',
  'loc_D84': 'CheckObjectCollision_Done',
  'loc_D86': 'CheckObjectCollision_Setup',
  'loc_D90': 'CheckObjectCollision_Loop',
  'loc_D9E': 'CheckObjectCollision_Hit',
  'loc_DB2': 'CheckObjectCollision_NoHit',
  'loc_DB6': 'CheckBoxOverlap2',
  'loc_DC8': 'CheckBoxOverlap2_XNeg',
  'loc_DD4': 'CheckBoxOverlap2_XTest',
  'loc_DFA': 'CheckBoxOverlap2_YNeg',
  'loc_E06': 'CheckBoxOverlap2_YTest',
  'loc_E18': 'CheckBoxOverlap2_Done',
  'loc_E1A': 'LinkCollisionPair',
  'loc_E4A': 'UnlinkCollisionPair',
  'loc_E62': 'UnlinkCollisionPair_Done',
  'loc_E9A': 'CheckOverlapDistance',
  'loc_EAC': 'CheckOverlapDistance_X',
  'loc_ECE': 'CheckOverlapDistance_Y',
  'loc_EE0': 'CheckOverlapDistance_Done',
  'loc_EE2': 'NormalizeAngle',
  'loc_EE6': 'NormalizeAngle_Abs',
  'loc_EEC': 'NormalizeAngle_Check',
  'loc_EF6': 'NormalizeAngle_Adjust',
  'loc_EFE': 'NormalizeAngle_Lookup',
  'loc_F16': 'NormalizeAngle_Combine',
  'loc_F1E': 'NormalizeAngle_Sign',
  'loc_F24': 'NormalizeAngle_Done',
  'loc_FA8': 'AngleToVector',
  'loc_FC0': 'AngleToVectorQ',
  'loc_104C': 'Atan2Fast_YSign',
  'loc_1054': 'Atan2Fast_Swap',
  'loc_105C': 'Atan2Fast_Compare',
  'loc_1066': 'Atan2Fast_Lookup',
  'loc_108C': 'CalcAngleToTarget',
  'loc_10A6': 'CalcAngleToTarget_YSign',
  'loc_10AE': 'CalcAngleToTarget_Swap',
  'loc_10B6': 'CalcAngleToTarget_Divide',
  'loc_10CC': 'CalcAngleToTarget_Compare',
  'loc_10D6': 'CalcAngleToTarget_NextBit',
  'loc_10E0': 'CalcAngleToTarget_Quad2',
  'loc_10EA': 'CalcAngleToTarget_Quad3',
  'loc_10F4': 'CalcAngleToTarget_Quad4',
  'loc_10FE': 'CalcAngleToTarget_Scale',
  'loc_1100': 'CalcAngleToTarget_Done',
  'loc_125E': 'ComputeDistance',
  'loc_126A': 'ComputeDistance_Swap',
  'loc_1270': 'ComputeDistance_Approx',
  'loc_1280': 'ComputeDistance_AbsY',
  'loc_1286': 'ComputeDistance_Compare',
  'loc_128E': 'ComputeDistance_Zero',
  'loc_1296': 'ComputeDistance_Div',
  'loc_12A8': 'ComputeDistance_SignX',
  'loc_12AE': 'ComputeDistance_SignY',
  'loc_12B4': 'ComputeDistance_Done',
  'loc_12DE': 'ComputeArcTrajectory',
  'loc_12EE': 'ComputeArcTrajectory_Div',
  'loc_1306': 'ComputeArcTrajectory_Zero',
  'loc_1308': 'ComputeArcTrajectory_Sign',
  'loc_130E': 'ComputeArcTrajectory_Done',
  'loc_1310': 'ComputeArcTrajectory_Calc',
  'loc_1330': 'ComputeArcTrajectory_Accum',
  'loc_1336': 'ComputeArcTrajectory_Next',
  'loc_134A': 'ComputeArcTrajectory_Scale',
  'loc_1358': 'ComputeArcTrajectory_ZeroD5',
  'loc_13A6': 'DecodePalette_Store',
  'loc_13AE': 'WriteTilemapEntryOffset',
  'loc_13EC': 'ResetPlayerForScene_Dispatch',
  'loc_13FA': 'ResetPlayerForScene_Dispatch2',
};
let total = 0;
for (const f of fs.readdirSync('src').filter(x => x.endsWith('.asm'))) {
  let txt = fs.readFileSync('src/' + f, 'latin1');
  let before = txt;
  for (const [old, next] of Object.entries(renames)) {
    txt = txt.split(old).join(next);
  }
  if (txt !== before) { fs.writeFileSync('src/' + f, txt); total++; console.log(f); }
}
// dedupe consecutive identical label lines (loc_108C was a redundant alias of CalcAngleToTarget)
for (const f of fs.readdirSync('src').filter(x => x.endsWith('.asm'))) {
  let lines = fs.readFileSync('src/' + f, 'latin1').split(/\r?\n/);
  let changed = false;
  for (let i = 0; i < lines.length - 1; i++) {
    if (lines[i].trim() === lines[i + 1].trim() && /^CalcAngleToTarget:$/.test(lines[i].trim())) {
      lines.splice(i, 1); changed = true; i--;
    }
  }
  if (changed) fs.writeFileSync('src/' + f, lines.join('\n'));
}
console.log('done');
