; ======================================================================
; src/palette_table.asm - AUTO-GENERATED by tools/regen_assets.js
; 252 x 17-byte packed palettes (LoadPalettes/DecodePalette format).
; Source: assets/palettes.json. Bit-exact when unmodified.
; ======================================================================
PaletteTable:
Palette_0:
	dc.b	$60,$26	; $599C (blue-high field)
	dc.b	$00,$c0,$e0,$92,$db,$6d,$18,$3b
	dc.b	$3f,$03,$06,$1f,$ef,$77,$ff
Palette_1:
	dc.b	$0e,$20	; $59AD (blue-high field)
	dc.b	$00,$0a,$54,$04,$17,$ff,$10,$60
	dc.b	$b8,$00,$51,$ec,$05,$07,$3f
Palette_2:
	dc.b	$41,$00	; $59BE (blue-high field)
	dc.b	$00,$0a,$14,$66,$b7,$0a,$94,$e6
	dc.b	$77,$20,$6a,$b3,$10,$fd,$ff
Palette_3:
	dc.b	$4d,$80	; $59CF (blue-high field)
	dc.b	$00,$01,$02,$0b,$5d,$ee,$80,$09
	dc.b	$d2,$ed,$76,$7f,$8c,$d5,$ff
Palette_4:
	dc.b	$7c,$10	; $59E0 (blue-high field)
	dc.b	$09,$0a,$54,$a6,$37,$5b,$ed,$10
	dc.b	$20,$3b,$00,$40,$80,$e0,$ff
Palette_5:
	dc.b	$7f,$f0	; $59F1 (blue-high field)
	dc.b	$00,$40,$80,$c0,$00,$40,$80,$c0
	dc.b	$c8,$d0,$d8,$e0,$e8,$f0,$ff
Palette_6:
	dc.b	$7e,$0c	; $5A02 (blue-high field)
	dc.b	$00,$92,$24,$6d,$28,$3c,$83,$40
	dc.b	$89,$1b,$40,$92,$e8,$fd,$ff
Palette_7:
	dc.b	$7c,$20	; $5A13 (blue-high field)
	dc.b	$00,$09,$12,$5b,$ed,$7f,$0a,$0b
	dc.b	$15,$37,$c7,$c7,$c7,$c7,$ff
Palette_8:
	dc.b	$41,$e0	; $5A24 (blue-high field)
	dc.b	$00,$01,$0b,$1d,$ae,$3f,$93,$0e
	dc.b	$a6,$08,$10,$59,$aa,$f5,$ff
Palette_9:
	dc.b	$79,$82	; $5A35 (blue-high field)
	dc.b	$00,$47,$92,$db,$52,$9b,$e4,$76
	dc.b	$bf,$40,$89,$12,$e4,$f6,$ff
Palette_10:
	dc.b	$41,$00	; $5A46 (blue-high field)
	dc.b	$00,$0a,$54,$66,$f7,$52,$e4,$cf
	dc.b	$67,$48,$50,$58,$aa,$f4,$ff
Palette_11:
	dc.b	$61,$d8	; $5A57 (blue-high field)
	dc.b	$00,$52,$e4,$76,$bf,$80,$01,$82
	dc.b	$d3,$0f,$57,$9f,$e7,$2f,$ff
Palette_12:
	dc.b	$41,$10	; $5A68 (blue-high field)
	dc.b	$01,$4a,$94,$dd,$6e,$b7,$10,$a2
	dc.b	$7d,$40,$88,$c9,$27,$06,$ff
Palette_13:
	dc.b	$61,$60	; $5A79 (blue-high field)
	dc.b	$00,$0a,$13,$5c,$a5,$36,$01,$c6
	dc.b	$16,$40,$48,$90,$e1,$2b,$ff
Palette_14:
	dc.b	$61,$10	; $5A8A (blue-high field)
	dc.b	$01,$4a,$93,$dc,$6e,$0a,$54,$a6
	dc.b	$37,$18,$6a,$fc,$10,$3e,$ff
Palette_15:
	dc.b	$4e,$20	; $5A9B (blue-high field)
	dc.b	$00,$09,$52,$9b,$e4,$2d,$01,$02
	dc.b	$03,$09,$9b,$ed,$05,$2f,$ff
Palette_16:
	dc.b	$7c,$20	; $5AAC (blue-high field)
	dc.b	$00,$0a,$53,$a5,$ee,$77,$02,$03
	dc.b	$05,$80,$12,$5b,$a4,$ed,$ff
Palette_17:
	dc.b	$79,$72	; $5ABD (blue-high field)
	dc.b	$01,$da,$4b,$95,$ec,$f5,$fe,$ee
	dc.b	$bf,$91,$da,$23,$2c,$75,$ff
Palette_18:
	dc.b	$71,$10	; $5ACE (blue-high field)
	dc.b	$01,$02,$4b,$95,$6f,$0a,$54,$ee
	dc.b	$bf,$18,$6a,$fc,$da,$f4,$ff
Palette_19:
	dc.b	$7f,$c4	; $5ADF (blue-high field)
	dc.b	$12,$a4,$7f,$26,$7f,$c0,$48,$91
	dc.b	$e3,$5a,$a3,$ec,$f5,$fe,$ff
Palette_20:
	dc.b	$70,$1e	; $5AF0 (blue-high field)
	dc.b	$40,$10,$59,$a2,$f4,$10,$18,$68
	dc.b	$ba,$53,$a5,$ee,$37,$7f,$ff
Palette_21:
	dc.b	$61,$20	; $5B01 (blue-high field)
	dc.b	$00,$01,$4a,$93,$dc,$6e,$52,$9b
	dc.b	$2d,$10,$18,$61,$aa,$3d,$bf
Palette_22:
	dc.b	$41,$20	; $5B12 (blue-high field)
	dc.b	$00,$01,$0b,$15,$66,$24,$52,$9b
	dc.b	$2d,$08,$10,$59,$a9,$fc,$ff
Palette_23:
	dc.b	$41,$60	; $5B23 (blue-high field)
	dc.b	$00,$01,$0b,$15,$66,$92,$f4,$ae
	dc.b	$3f,$08,$10,$58,$a9,$fc,$ff
Palette_24:
	dc.b	$49,$60	; $5B34 (blue-high field)
	dc.b	$00,$53,$9c,$e5,$66,$d2,$f4,$ae
	dc.b	$3f,$14,$d7,$af,$a9,$fc,$ff
Palette_25:
	dc.b	$41,$00	; $5B45 (blue-high field)
	dc.b	$00,$01,$0b,$15,$66,$12,$5b,$ad
	dc.b	$3f,$09,$10,$59,$a9,$fc,$7f
Palette_26:
	dc.b	$78,$20	; $5B56 (blue-high field)
	dc.b	$00,$09,$12,$5b,$ed,$36,$01,$0a
	dc.b	$53,$a5,$80,$12,$5b,$ed,$ff
Palette_27:
	dc.b	$78,$30	; $5B67 (blue-high field)
	dc.b	$00,$48,$91,$da,$23,$6c,$41,$82
	dc.b	$c3,$52,$9b,$2d,$c8,$e2,$f5
Palette_28:
	dc.b	$7f,$f0	; $5B78 (blue-high field)
	dc.b	$00,$40,$88,$91,$23,$6c,$1a,$63
	dc.b	$ac,$00,$40,$88,$d0,$e2,$fe
Palette_29:
	dc.b	$73,$18	; $5B89 (blue-high field)
	dc.b	$08,$51,$9a,$2c,$75,$00,$5b,$ed
	dc.b	$36,$7f,$42,$8b,$1e,$af,$ff
Palette_30:
	dc.b	$7f,$18	; $5B9A (blue-high field)
	dc.b	$08,$50,$98,$2a,$73,$00,$59,$eb
	dc.b	$7d,$be,$00,$88,$d9,$eb,$fe
Palette_31:
	dc.b	$63,$18	; $5BAB (blue-high field)
	dc.b	$08,$50,$98,$2a,$73,$09,$59,$eb
	dc.b	$7d,$be,$52,$9b,$e4,$2d,$be
Palette_32:
	dc.b	$74,$02	; $5BBC (blue-high field)
	dc.b	$00,$81,$0a,$13,$1d,$2e,$0f,$08
	dc.b	$90,$e9,$78,$82,$44,$9f,$ff
Palette_33:
	dc.b	$74,$8c	; $5BCD (blue-high field)
	dc.b	$00,$d0,$62,$f4,$3f,$1d,$0f,$d3
	dc.b	$90,$e9,$78,$82,$44,$9f,$ff
Palette_34:
	dc.b	$60,$e8	; $5BDE (blue-high field)
	dc.b	$00,$92,$db,$6d,$c0,$9b,$bc,$28
	dc.b	$90,$02,$4b,$94,$dd,$26,$ff
Palette_35:
	dc.b	$7c,$1e	; $5BEF (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_36:
	dc.b	$7c,$1e	; $5C00 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_37:
	dc.b	$7c,$1e	; $5C11 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_38:
	dc.b	$7c,$1e	; $5C22 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_39:
	dc.b	$7c,$1e	; $5C33 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_40:
	dc.b	$7c,$1e	; $5C44 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_41:
	dc.b	$7c,$1e	; $5C55 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_42:
	dc.b	$42,$20	; $5C66 (blue-high field)
	dc.b	$00,$09,$12,$5b,$ed,$36,$08,$51
	dc.b	$9a,$12,$0a,$15,$66,$f7,$ff
Palette_43:
	dc.b	$7c,$1e	; $5C77 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_44:
	dc.b	$7c,$1e	; $5C88 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_45:
	dc.b	$7c,$1e	; $5C99 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_46:
	dc.b	$7c,$1e	; $5CAA (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_47:
	dc.b	$7c,$1e	; $5CBB (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_48:
	dc.b	$61,$20	; $5CCC (blue-high field)
	dc.b	$01,$00,$b4,$53,$e5,$77,$11,$1a
	dc.b	$03,$0a,$14,$66,$f7,$7f,$ff
Palette_49:
	dc.b	$40,$30	; $5CDD (blue-high field)
	dc.b	$00,$00,$49,$92,$64,$ad,$3d,$3f
	dc.b	$2f,$27,$01,$02,$04,$0d,$ff
Palette_50:
	dc.b	$60,$20	; $5CEE (blue-high field)
	dc.b	$00,$01,$0a,$53,$9c,$2e,$0c,$15
	dc.b	$5e,$a6,$14,$66,$f7,$7f,$ff
Palette_51:
	dc.b	$40,$90	; $5CFF (blue-high field)
	dc.b	$01,$0b,$1d,$ae,$37,$0a,$14,$8c
	dc.b	$77,$08,$11,$5a,$a4,$ed,$bf
Palette_52:
	dc.b	$7d,$3e	; $5D10 (blue-high field)
	dc.b	$00,$01,$4b,$a5,$ee,$f7,$80,$c1
	dc.b	$0a,$c8,$51,$e3,$ec,$fe,$ff
Palette_53:
	dc.b	$7c,$00	; $5D21 (blue-high field)
	dc.b	$00,$01,$0a,$54,$65,$b6,$ff,$12
	dc.b	$a4,$ed,$76,$12,$a4,$f6,$ff
Palette_54:
	dc.b	$61,$c0	; $5D32 (blue-high field)
	dc.b	$00,$01,$0a,$54,$66,$b6,$93,$0e
	dc.b	$a6,$08,$50,$99,$eb,$35,$ff
Palette_55:
	dc.b	$7f,$bc	; $5D43 (blue-high field)
	dc.b	$00,$ca,$9d,$ee,$f7,$54,$a4,$2d
	dc.b	$76,$00,$92,$e4,$ed,$f6,$ff
Palette_56:
	dc.b	$7f,$bc	; $5D54 (blue-high field)
	dc.b	$00,$ca,$9d,$ee,$f7,$54,$e1,$73
	dc.b	$bc,$00,$92,$e4,$ed,$f6,$ff
Palette_57:
	dc.b	$7e,$3c	; $5D65 (blue-high field)
	dc.b	$00,$ca,$9d,$ee,$f7,$54,$48,$48
	dc.b	$91,$00,$92,$e4,$ed,$f6,$ff
Palette_58:
	dc.b	$7d,$20	; $5D76 (blue-high field)
	dc.b	$00,$48,$48,$91,$a4,$36,$80,$c1
	dc.b	$0a,$c8,$51,$e3,$ec,$f5,$ff
Palette_59:
	dc.b	$7d,$28	; $5D87 (blue-high field)
	dc.b	$00,$04,$07,$af,$a4,$36,$80,$c1
	dc.b	$0a,$c8,$51,$e3,$ec,$f5,$ff
Palette_60:
	dc.b	$7f,$fe	; $5D98 (blue-high field)
	dc.b	$00,$02,$9d,$ee,$f7,$54,$22,$6b
	dc.b	$f5,$00,$92,$e4,$ed,$f6,$ff
Palette_61:
	dc.b	$7f,$38	; $5DA9 (blue-high field)
	dc.b	$80,$a2,$eb,$34,$7d,$fe,$a7,$f7
	dc.b	$9f,$ef,$f7,$49,$92,$e4,$ff
Palette_62:
	dc.b	$41,$60	; $5DBA (blue-high field)
	dc.b	$00,$01,$02,$0b,$5d,$92,$f4,$ae
	dc.b	$3f,$08,$10,$58,$a9,$fc,$ff
Palette_63:
	dc.b	$40,$18	; $5DCB (blue-high field)
	dc.b	$51,$9a,$e3,$2d,$76,$09,$a8,$fb
	dc.b	$1f,$ef,$09,$4a,$8c,$d6,$bf
Palette_64:
	dc.b	$09,$82	; $5DDC (blue-high field)
	dc.b	$00,$ff,$10,$60,$a8,$f8,$c0,$10
	dc.b	$68,$44,$cf,$5f,$15,$a6,$f7
Palette_65:
	dc.b	$61,$02	; $5DED (blue-high field)
	dc.b	$00,$ff,$09,$53,$9c,$e5,$90,$d8
	dc.b	$20,$02,$04,$07,$87,$1f,$1b
Palette_66:
	dc.b	$08,$3a	; $5DFE (blue-high field)
	dc.b	$00,$ff,$88,$19,$2b,$7e,$19,$2b
	dc.b	$7e,$42,$c4,$47,$04,$07,$27
Palette_67:
	dc.b	$61,$b2	; $5E0F (blue-high field)
	dc.b	$00,$ff,$48,$91,$23,$74,$82,$0c
	dc.b	$df,$04,$07,$1f,$2f,$6d,$ff
Palette_68:
	dc.b	$0d,$e2	; $5E20 (blue-high field)
	dc.b	$00,$ff,$54,$9d,$e6,$2f,$10,$a2
	dc.b	$fc,$c0,$d0,$e8,$02,$04,$c7
Palette_69:
	dc.b	$0e,$02	; $5E31 (blue-high field)
	dc.b	$00,$ff,$03,$05,$07,$17,$1f,$27
	dc.b	$37,$03,$47,$e7,$10,$20,$38
Palette_70:
	dc.b	$68,$3a	; $5E42 (blue-high field)
	dc.b	$00,$ff,$d2,$1b,$64,$ad,$15,$1e
	dc.b	$2f,$40,$05,$40,$80,$80,$d8
Palette_71:
	dc.b	$68,$3a	; $5E53 (blue-high field)
	dc.b	$00,$ff,$d2,$23,$6c,$b5,$0d,$16
	dc.b	$2f,$83,$c4,$86,$80,$80,$d8
Palette_72:
	dc.b	$00,$22	; $5E64 (blue-high field)
	dc.b	$00,$ff,$54,$9d,$e6,$2f,$10,$22
	dc.b	$3c,$17,$27,$37,$04,$05,$c7
Palette_73:
	dc.b	$09,$ba	; $5E75 (blue-high field)
	dc.b	$00,$ff,$c1,$53,$9c,$ef,$90,$20
	dc.b	$74,$1f,$af,$37,$02,$05,$07
Palette_74:
	dc.b	$64,$32	; $5E86 (blue-high field)
	dc.b	$00,$ff,$88,$d0,$20,$70,$54,$1d
	dc.b	$37,$9d,$2f,$c7,$80,$c8,$e0
Palette_75:
	dc.b	$7f,$0e	; $5E97 (blue-high field)
	dc.b	$00,$5d,$a6,$ef,$09,$52,$9b,$e4
	dc.b	$76,$ed,$a4,$ed,$a4,$ed,$ff
Palette_76:
	dc.b	$7c,$1e	; $5EA8 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_77:
	dc.b	$7c,$1e	; $5EB9 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_78:
	dc.b	$7c,$1e	; $5ECA (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_79:
	dc.b	$61,$02	; $5EDB (blue-high field)
	dc.b	$00,$ff,$0a,$54,$9d,$e6,$90,$d8
	dc.b	$20,$02,$04,$07,$87,$1f,$1b
Palette_80:
	dc.b	$71,$10	; $5EEC (blue-high field)
	dc.b	$00,$02,$4b,$95,$27,$0a,$54,$ee
	dc.b	$7f,$18,$6a,$fc,$9b,$e4,$ff
Palette_81:
	dc.b	$7f,$1c	; $5EFD (blue-high field)
	dc.b	$00,$89,$09,$9b,$ad,$4a,$93,$dc
	dc.b	$6e,$5a,$a3,$ec,$f5,$fe,$ff
Palette_82:
	dc.b	$7d,$18	; $5F0E (blue-high field)
	dc.b	$08,$51,$9a,$2c,$75,$38,$13,$a5
	dc.b	$36,$07,$47,$c7,$c5,$6d,$ff
Palette_83:
	dc.b	$7f,$38	; $5F1F (blue-high field)
	dc.b	$81,$40,$e3,$75,$be,$ed,$05,$c3
	dc.b	$4d,$9e,$ef,$49,$92,$db,$ff
Palette_84:
	dc.b	$78,$a4	; $5F30 (blue-high field)
	dc.b	$81,$c2,$e8,$66,$f7,$e7,$db,$6d
	dc.b	$0a,$04,$16,$03,$8d,$de,$ff
Palette_85:
	dc.b	$42,$18	; $5F41 (blue-high field)
	dc.b	$08,$51,$9a,$2c,$75,$58,$a8,$fb
	dc.b	$67,$37,$09,$4a,$8c,$d6,$bf
Palette_86:
	dc.b	$43,$98	; $5F52 (blue-high field)
	dc.b	$08,$51,$9a,$2c,$75,$27,$88,$10
	dc.b	$a0,$f2,$09,$4a,$4c,$96,$ff
Palette_87:
	dc.b	$47,$00	; $5F63 (blue-high field)
	dc.b	$00,$03,$05,$08,$10,$6a,$bc,$c0
	dc.b	$09,$52,$9b,$09,$5b,$ed,$ff
Palette_88:
	dc.b	$7e,$20	; $5F74 (blue-high field)
	dc.b	$00,$0a,$53,$a5,$ee,$77,$02,$03
	dc.b	$05,$5a,$a3,$ec,$f5,$fe,$ff
Palette_89:
	dc.b	$78,$20	; $5F85 (blue-high field)
	dc.b	$00,$0a,$53,$a5,$ee,$77,$18,$28
	dc.b	$38,$89,$d2,$1b,$ad,$f6,$ff
Palette_90:
	dc.b	$70,$38	; $5F96 (blue-high field)
	dc.b	$00,$91,$da,$23,$6c,$b5,$51,$59
	dc.b	$a2,$12,$a4,$ed,$36,$7f,$ff
Palette_91:
	dc.b	$7f,$0e	; $5FA7 (blue-high field)
	dc.b	$00,$5d,$a6,$ef,$09,$52,$9b,$e4
	dc.b	$76,$f6,$ed,$a4,$a4,$ed,$ff
Palette_92:
	dc.b	$67,$20	; $5FB8 (blue-high field)
	dc.b	$00,$02,$04,$0e,$5f,$5b,$3d,$3f
	dc.b	$09,$db,$ed,$12,$a4,$36,$ff
Palette_93:
	dc.b	$67,$e0	; $5FC9 (blue-high field)
	dc.b	$00,$02,$04,$0e,$5f,$52,$e4,$f6
	dc.b	$09,$db,$ed,$12,$a4,$36,$ff
Palette_94:
	dc.b	$7a,$00	; $5FDA (blue-high field)
	dc.b	$08,$51,$9a,$e3,$00,$01,$03,$16
	dc.b	$36,$2c,$81,$43,$94,$89,$7f
Palette_95:
	dc.b	$79,$80	; $5FEB (blue-high field)
	dc.b	$08,$51,$9a,$e3,$00,$12,$a4,$2d
	dc.b	$ab,$40,$81,$43,$94,$89,$fe
Palette_96:
	dc.b	$60,$d0	; $5FFC (blue-high field)
	dc.b	$00,$09,$52,$e4,$2d,$c0,$08,$9a
	dc.b	$02,$04,$ce,$15,$36,$2e,$76
Palette_97:
	dc.b	$7f,$82	; $600D (blue-high field)
	dc.b	$00,$c0,$05,$16,$27,$2f,$3f,$78
	dc.b	$c0,$c9,$d2,$db,$e4,$ed,$ff
Palette_98:
	dc.b	$52,$00	; $601E (blue-high field)
	dc.b	$00,$48,$91,$da,$00,$01,$0a,$9c
	dc.b	$f7,$23,$80,$c9,$12,$9b,$3f
Palette_99:
	dc.b	$51,$80	; $602F (blue-high field)
	dc.b	$08,$48,$91,$da,$00,$52,$e4,$2d
	dc.b	$2d,$00,$80,$c9,$12,$9b,$7f
Palette_100:
	dc.b	$40,$00	; $6040 (blue-high field)
	dc.b	$00,$09,$52,$9b,$e4,$40,$89,$d2
	dc.b	$02,$4b,$94,$54,$a6,$e5,$76
Palette_101:
	dc.b	$7d,$10	; $6051 (blue-high field)
	dc.b	$01,$0a,$54,$ee,$bf,$10,$61,$8f
	dc.b	$67,$3f,$08,$99,$eb,$fe,$ff
Palette_102:
	dc.b	$7e,$30	; $6062 (blue-high field)
	dc.b	$00,$48,$91,$da,$23,$b5,$0a,$54
	dc.b	$ee,$5a,$a3,$ec,$f5,$fe,$ff
Palette_103:
	dc.b	$61,$1c	; $6073 (blue-high field)
	dc.b	$00,$d0,$61,$f5,$f7,$0a,$54,$a6
	dc.b	$37,$10,$18,$6a,$fc,$3e,$ff
Palette_104:
	dc.b	$61,$10	; $6084 (blue-high field)
	dc.b	$01,$4a,$93,$dc,$6e,$18,$6a,$fc
	dc.b	$03,$0a,$14,$66,$f7,$7f,$ff
Palette_105:
	dc.b	$79,$10	; $6095 (blue-high field)
	dc.b	$00,$02,$4b,$95,$6f,$12,$5b,$a4
	dc.b	$36,$91,$da,$23,$2c,$75,$ff
Palette_106:
	dc.b	$67,$20	; $60A6 (blue-high field)
	dc.b	$00,$0a,$53,$a5,$ee,$77,$45,$c6
	dc.b	$67,$c0,$e0,$16,$e7,$77,$ff
Palette_107:
	dc.b	$7e,$30	; $60B7 (blue-high field)
	dc.b	$00,$40,$88,$91,$23,$6c,$01,$02
	dc.b	$03,$00,$40,$88,$d0,$e2,$f5
Palette_108:
	dc.b	$40,$00	; $60C8 (blue-high field)
	dc.b	$00,$08,$51,$9a,$ac,$ff,$0f,$1f
	dc.b	$37,$01,$02,$04,$88,$91,$bf
Palette_109:
	dc.b	$7f,$3e	; $60D9 (blue-high field)
	dc.b	$81,$0c,$9e,$ef,$f7,$be,$00,$f7
	dc.b	$9f,$ef,$f7,$40,$92,$e4,$ff
Palette_110:
	dc.b	$40,$00	; $60EA (blue-high field)
	dc.b	$00,$01,$0b,$5d,$ae,$f7,$04,$07
	dc.b	$17,$08,$10,$59,$a9,$fc,$ff
Palette_111:
	dc.b	$40,$00	; $60FB (blue-high field)
	dc.b	$00,$51,$9a,$a3,$ec,$80,$80,$f7
	dc.b	$02,$04,$96,$00,$08,$51,$ff
Palette_112:
	dc.b	$70,$00	; $610C (blue-high field)
	dc.b	$00,$00,$09,$12,$a4,$ed,$00,$01
	dc.b	$0a,$5c,$40,$c9,$12,$a4,$7f
Palette_113:
	dc.b	$60,$00	; $611D (blue-high field)
	dc.b	$00,$00,$00,$09,$5b,$a4,$00,$00
	dc.b	$01,$13,$00,$80,$c9,$5b,$36
Palette_114:
	dc.b	$20,$00	; $612E (blue-high field)
	dc.b	$00,$00,$00,$00,$12,$5b,$00,$00
	dc.b	$00,$0a,$00,$40,$80,$12,$ed
Palette_115:
	dc.b	$00,$00	; $613F (blue-high field)
	dc.b	$00,$00,$00,$00,$09,$12,$00,$00
	dc.b	$00,$01,$00,$00,$40,$c9,$5b
Palette_116:
	dc.b	$00,$00	; $6150 (blue-high field)
	dc.b	$00,$00,$00,$00,$00,$09,$00,$00
	dc.b	$00,$01,$00,$00,$00,$80,$12
Palette_117:
	dc.b	$00,$00	; $6161 (blue-high field)
	dc.b	$00,$00,$00,$00,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$00,$40,$12
Palette_118:
	dc.b	$00,$00	; $6172 (blue-high field)
	dc.b	$00,$00,$00,$00,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$00,$00,$00
Palette_119:
	dc.b	$7d,$38	; $6183 (blue-high field)
	dc.b	$40,$8c,$d5,$66,$ef,$f7,$80,$c1
	dc.b	$0a,$c8,$51,$e3,$ec,$f5,$ff
Palette_120:
	dc.b	$70,$40	; $6194 (blue-high field)
	dc.b	$00,$01,$0a,$53,$9c,$c3,$55,$64
	dc.b	$f6,$40,$88,$d1,$63,$f5,$ff
Palette_121:
	dc.b	$71,$c4	; $61A5 (blue-high field)
	dc.b	$12,$a4,$36,$26,$7f,$c0,$48,$91
	dc.b	$e3,$40,$89,$d2,$64,$f6,$ff
Palette_122:
	dc.b	$79,$20	; $61B6 (blue-high field)
	dc.b	$00,$01,$0a,$53,$83,$15,$12,$a4
	dc.b	$36,$40,$89,$12,$ed,$f6,$ff
Palette_123:
	dc.b	$79,$20	; $61C7 (blue-high field)
	dc.b	$00,$02,$09,$51,$9a,$2c,$12,$a4
	dc.b	$36,$40,$89,$12,$ed,$f6,$ff
Palette_124:
	dc.b	$71,$00	; $61D8 (blue-high field)
	dc.b	$00,$01,$0a,$5d,$ae,$09,$5b,$ed
	dc.b	$36,$01,$4a,$54,$c0,$e0,$ff
Palette_125:
	dc.b	$78,$00	; $61E9 (blue-high field)
	dc.b	$00,$01,$0a,$5d,$ae,$09,$12,$64
	dc.b	$f6,$40,$89,$12,$ed,$f6,$ff
Palette_126:
	dc.b	$79,$00	; $61FA (blue-high field)
	dc.b	$00,$01,$03,$04,$0d,$09,$12,$a4
	dc.b	$36,$40,$89,$12,$ed,$f6,$ff
Palette_127:
	dc.b	$78,$10	; $620B (blue-high field)
	dc.b	$00,$41,$82,$c3,$0c,$09,$12,$64
	dc.b	$f6,$40,$89,$12,$ed,$f6,$ff
Palette_128:
	dc.b	$73,$24	; $621C (blue-high field)
	dc.b	$00,$3f,$c7,$52,$9b,$2d,$48,$d1
	dc.b	$23,$75,$40,$c9,$12,$5b,$ff
Palette_129:
	dc.b	$71,$22	; $622D (blue-high field)
	dc.b	$00,$d2,$67,$92,$db,$6d,$10,$ab
	dc.b	$7e,$4b,$94,$dd,$6f,$b7,$ff
Palette_130:
	dc.b	$71,$34	; $623E (blue-high field)
	dc.b	$00,$16,$38,$d1,$23,$75,$52,$e4
	dc.b	$76,$40,$81,$ca,$13,$5c,$bf
Palette_131:
	dc.b	$78,$10	; $624F (blue-high field)
	dc.b	$01,$4b,$95,$de,$6f,$3d,$10,$18
	dc.b	$73,$40,$80,$09,$52,$9b,$ff
Palette_132:
	dc.b	$7c,$4c	; $6260 (blue-high field)
	dc.b	$00,$92,$24,$6d,$50,$98,$28,$0f
	dc.b	$27,$3f,$40,$92,$e8,$fd,$ff
Palette_133:
	dc.b	$70,$b0	; $6271 (blue-high field)
	dc.b	$00,$0a,$54,$a6,$37,$7f,$df,$6f
	dc.b	$1c,$2f,$bf,$c8,$a0,$f3,$ff
Palette_134:
	dc.b	$7f,$3c	; $6282 (blue-high field)
	dc.b	$40,$c0,$00,$ed,$f6,$be,$00,$f7
	dc.b	$9f,$ef,$f7,$49,$92,$e4,$ff
Palette_135:
	dc.b	$62,$08	; $6293 (blue-high field)
	dc.b	$40,$81,$c2,$44,$44,$ce,$00,$25
	dc.b	$b7,$3f,$14,$5d,$a6,$37,$ff
Palette_136:
	dc.b	$70,$e2	; $62A4 (blue-high field)
	dc.b	$00,$c0,$20,$30,$3c,$4b,$dd,$ee
	dc.b	$1e,$2f,$bf,$c5,$47,$a7,$ff
Palette_137:
	dc.b	$7c,$8c	; $62B5 (blue-high field)
	dc.b	$00,$d8,$20,$74,$14,$1f,$b7,$3f
	dc.b	$04,$05,$07,$e0,$e8,$fd,$ff
Palette_138:
	dc.b	$7f,$de	; $62C6 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$57,$9f
	dc.b	$ef,$d0,$e0,$e8,$f4,$fd,$ff
Palette_139:
	dc.b	$79,$c0	; $62D7 (blue-high field)
	dc.b	$00,$04,$17,$37,$5b,$ed,$76,$d2
	dc.b	$f4,$40,$80,$02,$8c,$dd,$ff
Palette_140:
	dc.b	$78,$10	; $62E8 (blue-high field)
	dc.b	$00,$11,$a3,$f5,$3f,$05,$0f,$27
	dc.b	$bf,$02,$0b,$c7,$c5,$6d,$ff
Palette_141:
	dc.b	$41,$98	; $62F9 (blue-high field)
	dc.b	$00,$92,$db,$6d,$b6,$30,$3e,$00
	dc.b	$c0,$01,$0a,$13,$1d,$2f,$ff
Palette_142:
	dc.b	$61,$98	; $630A (blue-high field)
	dc.b	$00,$92,$db,$6d,$b6,$38,$c0,$9b
	dc.b	$f4,$02,$4b,$94,$dd,$26,$ff
Palette_143:
	dc.b	$41,$18	; $631B (blue-high field)
	dc.b	$00,$82,$c3,$0c,$55,$09,$12,$a4
	dc.b	$36,$01,$02,$03,$04,$05,$ff
Palette_144:
	dc.b	$41,$10	; $632C (blue-high field)
	dc.b	$00,$41,$82,$c3,$0c,$09,$12,$a4
	dc.b	$36,$00,$00,$00,$00,$00,$ff
Palette_145:
	dc.b	$60,$18	; $633D (blue-high field)
	dc.b	$00,$52,$9b,$2d,$76,$01,$0a,$53
	dc.b	$9d,$a7,$40,$88,$c8,$11,$ff
Palette_146:
	dc.b	$63,$f8	; $634E (blue-high field)
	dc.b	$00,$52,$9b,$2d,$76,$00,$9b,$e4
	dc.b	$ed,$f6,$40,$88,$c8,$11,$ff
Palette_147:
	dc.b	$61,$d8	; $635F (blue-high field)
	dc.b	$49,$51,$9a,$2c,$be,$c2,$94,$a5
	dc.b	$03,$0a,$14,$66,$f7,$7f,$ff
Palette_148:
	dc.b	$7c,$20	; $6370 (blue-high field)
	dc.b	$00,$09,$12,$5b,$ed,$36,$01,$0a
	dc.b	$53,$a5,$c0,$d8,$ea,$f3,$ff
Palette_149:
	dc.b	$7c,$1e	; $6381 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_150:
	dc.b	$7c,$1e	; $6392 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_151:
	dc.b	$7c,$1e	; $63A3 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_152:
	dc.b	$7c,$1e	; $63B4 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_153:
	dc.b	$7c,$1e	; $63C5 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_154:
	dc.b	$7c,$1e	; $63D6 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_155:
	dc.b	$7c,$1e	; $63E7 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_156:
	dc.b	$7c,$1e	; $63F8 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_157:
	dc.b	$7c,$1e	; $6409 (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_158:
	dc.b	$7c,$1e	; $641A (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_159:
	dc.b	$7c,$1e	; $642B (blue-high field)
	dc.b	$00,$c0,$e8,$f8,$78,$38,$3d,$3f
	dc.b	$2f,$07,$47,$c7,$c5,$6d,$ff
Palette_160:
	dc.b	$00,$00	; $643C (blue-high field)
	dc.b	$64,$5c,$00,$00,$64,$a8,$00,$00
	dc.b	$64,$e4,$00,$00,$65,$30,$00
Palette_161:
	dc.b	$00,$65	; $644D (blue-high field)
	dc.b	$78,$00,$00,$65,$c0,$00,$00,$65
	dc.b	$ee,$00,$00,$66,$16,$04,$04
Palette_162:
	dc.b	$00,$64	; $645E (blue-high field)
	dc.b	$0e,$ec,$00,$6a,$0e,$64,$00,$6c
	dc.b	$0e,$a8,$00,$6e,$0e,$ca,$04
Palette_163:
	dc.b	$04,$00	; $646F (blue-high field)
	dc.b	$64,$0e,$ca,$00,$6a,$0e,$ec,$00
	dc.b	$6c,$0e,$64,$00,$6e,$0e,$a8
Palette_164:
	dc.b	$04,$04	; $6480 (blue-high field)
	dc.b	$00,$64,$0e,$a8,$00,$6a,$0e,$ca
	dc.b	$00,$6c,$0e,$ec,$00,$6e,$0e
Palette_165:
	dc.b	$64,$04	; $6491 (blue-high field)
	dc.b	$04,$00,$64,$0e,$64,$00,$6a,$0e
	dc.b	$a8,$00,$6c,$0e,$ca,$00,$6e
Palette_166:
	dc.b	$0e,$ec	; $64A2 (blue-high field)
	dc.b	$00,$02,$ff,$b6,$04,$03,$00,$54
	dc.b	$00,$00,$00,$56,$00,$02,$00
Palette_167:
	dc.b	$58,$02	; $64B3 (blue-high field)
	dc.b	$24,$04,$03,$00,$54,$00,$00,$00
	dc.b	$56,$00,$00,$00,$58,$00,$02
Palette_168:
	dc.b	$04,$03	; $64C4 (blue-high field)
	dc.b	$00,$54,$00,$00,$00,$56,$00,$02
	dc.b	$00,$58,$02,$24,$04,$03,$00
Palette_169:
	dc.b	$54,$00	; $64D5 (blue-high field)
	dc.b	$02,$00,$56,$02,$24,$00,$58,$02
	dc.b	$28,$00,$02,$ff,$c6,$06,$04
Palette_170:
	dc.b	$00,$4c	; $64E6 (blue-high field)
	dc.b	$04,$ee,$00,$4e,$00,$0a,$00,$50
	dc.b	$00,$2e,$00,$52,$00,$8e,$06
Palette_171:
	dc.b	$04,$00	; $64F7 (blue-high field)
	dc.b	$4c,$00,$8e,$00,$4e,$04,$ee,$00
	dc.b	$50,$00,$0a,$00,$52,$00,$2e
Palette_172:
	dc.b	$06,$04	; $6508 (blue-high field)
	dc.b	$00,$4c,$00,$2e,$00,$4e,$00,$8e
	dc.b	$00,$50,$04,$ee,$00,$52,$00
Palette_173:
	dc.b	$0a,$06	; $6519 (blue-high field)
	dc.b	$04,$00,$4c,$00,$0a,$00,$4e,$00
	dc.b	$2e,$00,$50,$00,$8e,$00,$52
Palette_174:
	dc.b	$04,$ee	; $652A (blue-high field)
	dc.b	$00,$02,$ff,$b6,$10,$01,$00,$5c
	dc.b	$00,$02,$10,$02,$00,$5a,$00
Palette_175:
	dc.b	$02,$00	; $653B (blue-high field)
	dc.b	$5c,$00,$04,$10,$03,$00,$58,$00
	dc.b	$02,$00,$5a,$00,$04,$00,$5c
Palette_176:
	dc.b	$00,$06	; $654C (blue-high field)
	dc.b	$10,$04,$00,$56,$00,$02,$00,$58
	dc.b	$00,$04,$00,$5a,$00,$06,$00
Palette_177:
	dc.b	$5c,$00	; $655D (blue-high field)
	dc.b	$08,$01,$05,$00,$56,$00,$02,$00
	dc.b	$58,$00,$04,$00,$56,$00,$06
Palette_178:
	dc.b	$00,$5a	; $656E (blue-high field)
	dc.b	$00,$08,$00,$5c,$00,$0a,$ff,$00
	dc.b	$10,$05,$00,$56,$00,$00,$00
Palette_179:
	dc.b	$58,$00	; $657F (blue-high field)
	dc.b	$02,$00,$56,$00,$04,$00,$5a,$00
	dc.b	$06,$00,$5c,$00,$08,$10,$04
Palette_180:
	dc.b	$00,$56	; $6590 (blue-high field)
	dc.b	$00,$00,$00,$58,$00,$02,$00,$5a
	dc.b	$00,$04,$00,$5c,$00,$06,$10
Palette_181:
	dc.b	$03,$00	; $65A1 (blue-high field)
	dc.b	$58,$00,$00,$00,$5a,$00,$02,$00
	dc.b	$5c,$00,$04,$10,$02,$00,$5a
Palette_182:
	dc.b	$00,$00	; $65B2 (blue-high field)
	dc.b	$00,$5c,$00,$02,$01,$01,$00,$5c
	dc.b	$00,$00,$ff,$00,$03,$03,$00
Palette_183:
	dc.b	$4e,$0c	; $65C3 (blue-high field)
	dc.b	$e8,$00,$50,$08,$a0,$00,$52,$04
	dc.b	$40,$03,$03,$00,$4e,$08,$a0
Palette_184:
	dc.b	$00,$50	; $65D4 (blue-high field)
	dc.b	$04,$40,$00,$52,$0c,$e8,$03,$03
	dc.b	$00,$4e,$04,$40,$00,$50,$0c
Palette_185:
	dc.b	$e8,$00	; $65E5 (blue-high field)
	dc.b	$50,$08,$a0,$00,$02,$ff,$d4,$01
	dc.b	$09,$00,$14,$0a,$00,$00,$12
Palette_186:
	dc.b	$0c,$00	; $65F6 (blue-high field)
	dc.b	$00,$10,$0e,$00,$00,$0e,$0e,$20
	dc.b	$00,$0c,$0e,$40,$00,$0a,$0e
Palette_187:
	dc.b	$60,$00	; $6607 (blue-high field)
	dc.b	$08,$0e,$80,$00,$06,$0e,$a0,$00
	dc.b	$04,$0e,$c0,$ff,$00,$02,$09
Palette_188:
	dc.b	$00,$14	; $6618 (blue-high field)
	dc.b	$0c,$00,$00,$12,$0e,$00,$00,$10
	dc.b	$0e,$20,$00,$0e,$0e,$40,$00
Palette_189:
	dc.b	$0c,$0e	; $6629 (blue-high field)
	dc.b	$60,$00,$0a,$0e,$80,$00,$08,$0e
	dc.b	$a0,$00,$06,$0e,$c0,$00,$04
Palette_190:
	dc.b	$0e,$a0	; $663A (blue-high field)
	dc.b	$02,$09,$00,$14,$0e,$00,$00,$12
	dc.b	$0e,$20,$00,$10,$0e,$40,$00
Palette_191:
	dc.b	$0e,$0e	; $664B (blue-high field)
	dc.b	$60,$00,$0c,$0e,$80,$00,$0a,$0e
	dc.b	$a0,$00,$08,$0e,$c0,$00,$06
Palette_192:
	dc.b	$0e,$a0	; $665C (blue-high field)
	dc.b	$00,$04,$0e,$80,$02,$09,$00,$14
	dc.b	$0e,$20,$00,$12,$0e,$40,$00
Palette_193:
	dc.b	$10,$0e	; $666D (blue-high field)
	dc.b	$60,$00,$0e,$0e,$80,$00,$0c,$0e
	dc.b	$a0,$00,$0a,$0e,$c0,$00,$08
Palette_194:
	dc.b	$0e,$a0	; $667E (blue-high field)
	dc.b	$00,$06,$0e,$80,$00,$04,$0e,$60
	dc.b	$02,$09,$00,$14,$0e,$40,$00
Palette_195:
	dc.b	$12,$0e	; $668F (blue-high field)
	dc.b	$60,$00,$10,$0e,$80,$00,$0e,$0e
	dc.b	$a0,$00,$0c,$0e,$c0,$00,$0a
Palette_196:
	dc.b	$0e,$a0	; $66A0 (blue-high field)
	dc.b	$00,$08,$0e,$80,$00,$06,$0e,$60
	dc.b	$00,$04,$0e,$40,$02,$09,$00
Palette_197:
	dc.b	$14,$0e	; $66B1 (blue-high field)
	dc.b	$60,$00,$12,$0e,$80,$00,$10,$0e
	dc.b	$a0,$00,$0e,$0e,$c0,$00,$0c
Palette_198:
	dc.b	$0e,$a0	; $66C2 (blue-high field)
	dc.b	$00,$0a,$0e,$80,$00,$08,$0e,$60
	dc.b	$00,$06,$0e,$40,$00,$04,$0e
Palette_199:
	dc.b	$20,$02	; $66D3 (blue-high field)
	dc.b	$09,$00,$14,$0e,$80,$00,$12,$0e
	dc.b	$a0,$00,$10,$0e,$c0,$00,$0e
Palette_200:
	dc.b	$0e,$a0	; $66E4 (blue-high field)
	dc.b	$00,$0c,$0e,$80,$00,$0a,$0e,$60
	dc.b	$00,$08,$0e,$40,$00,$06,$0e
Palette_201:
	dc.b	$20,$00	; $66F5 (blue-high field)
	dc.b	$04,$0e,$00,$02,$09,$00,$14,$0e
	dc.b	$a0,$00,$12,$0e,$c0,$00,$10
Palette_202:
	dc.b	$0e,$a0	; $6706 (blue-high field)
	dc.b	$00,$0e,$0e,$80,$00,$0c,$0e,$60
	dc.b	$00,$0a,$0e,$40,$00,$08,$0e
Palette_203:
	dc.b	$20,$00	; $6717 (blue-high field)
	dc.b	$06,$0e,$00,$00,$04,$0c,$00,$02
	dc.b	$09,$00,$14,$0e,$c0,$00,$12
Palette_204:
	dc.b	$0e,$a0	; $6728 (blue-high field)
	dc.b	$00,$10,$0e,$80,$00,$0e,$0e,$60
	dc.b	$00,$0c,$0e,$40,$00,$0a,$0e
Palette_205:
	dc.b	$20,$00	; $6739 (blue-high field)
	dc.b	$08,$0e,$00,$00,$06,$0c,$00,$00
	dc.b	$04,$0a,$00,$02,$09,$00,$14
Palette_206:
	dc.b	$0e,$a0	; $674A (blue-high field)
	dc.b	$00,$12,$0e,$80,$00,$10,$0e,$60
	dc.b	$00,$0e,$0e,$40,$00,$0c,$0e
Palette_207:
	dc.b	$20,$00	; $675B (blue-high field)
	dc.b	$0a,$0e,$00,$00,$08,$0c,$00,$00
	dc.b	$06,$0a,$00,$00,$04,$08,$00
Palette_208:
	dc.b	$02,$09	; $676C (blue-high field)
	dc.b	$00,$14,$0e,$80,$00,$12,$0e,$60
	dc.b	$00,$10,$0e,$40,$00,$0e,$0e
Palette_209:
	dc.b	$20,$00	; $677D (blue-high field)
	dc.b	$0c,$0e,$00,$00,$0a,$0c,$00,$00
	dc.b	$08,$0a,$00,$00,$06,$08,$00
Palette_210:
	dc.b	$00,$04	; $678E (blue-high field)
	dc.b	$06,$00,$02,$09,$00,$14,$0e,$60
	dc.b	$00,$12,$0e,$40,$00,$10,$0e
Palette_211:
	dc.b	$20,$00	; $679F (blue-high field)
	dc.b	$0e,$0e,$00,$00,$0c,$0c,$00,$00
	dc.b	$0a,$0a,$00,$00,$08,$08,$00
Palette_212:
	dc.b	$00,$06	; $67B0 (blue-high field)
	dc.b	$06,$00,$00,$04,$08,$00,$02,$09
	dc.b	$00,$14,$0e,$40,$00,$12,$0e
Palette_213:
	dc.b	$20,$00	; $67C1 (blue-high field)
	dc.b	$10,$0e,$00,$00,$0e,$0c,$00,$00
	dc.b	$0c,$0a,$00,$00,$0a,$08,$00
Palette_214:
	dc.b	$00,$08	; $67D2 (blue-high field)
	dc.b	$06,$00,$00,$06,$08,$00,$00,$04
	dc.b	$0a,$00,$02,$09,$00,$14,$0e
Palette_215:
	dc.b	$20,$00	; $67E3 (blue-high field)
	dc.b	$12,$0e,$00,$00,$10,$0c,$00,$00
	dc.b	$0e,$0a,$00,$00,$0c,$08,$00
Palette_216:
	dc.b	$00,$0a	; $67F4 (blue-high field)
	dc.b	$06,$00,$00,$08,$08,$00,$00,$06
	dc.b	$0a,$00,$00,$04,$0c,$00,$02
Palette_217:
	dc.b	$09,$00	; $6805 (blue-high field)
	dc.b	$14,$0e,$00,$00,$12,$0c,$00,$00
	dc.b	$10,$0a,$00,$00,$0e,$08,$00
Palette_218:
	dc.b	$00,$0c	; $6816 (blue-high field)
	dc.b	$06,$00,$00,$0a,$08,$00,$00,$08
	dc.b	$0a,$00,$00,$06,$0c,$00,$00
Palette_219:
	dc.b	$04,$0e	; $6827 (blue-high field)
	dc.b	$00,$02,$09,$00,$14,$0c,$00,$00
	dc.b	$12,$0a,$00,$00,$10,$08,$00
Palette_220:
	dc.b	$00,$0e	; $6838 (blue-high field)
	dc.b	$06,$00,$00,$0c,$08,$00,$00,$0a
	dc.b	$0a,$00,$00,$08,$0c,$00,$00
Palette_221:
	dc.b	$06,$0e	; $6849 (blue-high field)
	dc.b	$00,$00,$04,$0e,$20,$02,$09,$00
	dc.b	$14,$0a,$00,$00,$12,$08,$00
Palette_222:
	dc.b	$00,$10	; $685A (blue-high field)
	dc.b	$06,$00,$00,$0e,$08,$00,$00,$0c
	dc.b	$0a,$00,$00,$0a,$0c,$00,$00
Palette_223:
	dc.b	$08,$0e	; $686B (blue-high field)
	dc.b	$00,$00,$06,$0e,$20,$00,$04,$0e
	dc.b	$40,$02,$09,$00,$14,$08,$00
Palette_224:
	dc.b	$00,$12	; $687C (blue-high field)
	dc.b	$06,$00,$00,$10,$08,$00,$00,$0e
	dc.b	$0a,$00,$00,$0c,$0c,$00,$00
Palette_225:
	dc.b	$0a,$0e	; $688D (blue-high field)
	dc.b	$00,$00,$08,$0e,$20,$00,$06,$0e
	dc.b	$40,$00,$04,$0e,$60,$02,$09
Palette_226:
	dc.b	$00,$14	; $689E (blue-high field)
	dc.b	$06,$00,$00,$12,$08,$00,$00,$10
	dc.b	$0a,$00,$00,$0e,$0c,$00,$00
Palette_227:
	dc.b	$0c,$0e	; $68AF (blue-high field)
	dc.b	$00,$00,$0a,$0e,$20,$00,$08,$0e
	dc.b	$40,$00,$06,$0e,$60,$00,$04
Palette_228:
	dc.b	$0e,$80	; $68C0 (blue-high field)
	dc.b	$02,$09,$00,$14,$08,$00,$00,$12
	dc.b	$0a,$00,$00,$10,$0c,$00,$00
Palette_229:
	dc.b	$0e,$0e	; $68D1 (blue-high field)
	dc.b	$00,$00,$0c,$0e,$20,$00,$0a,$0e
	dc.b	$40,$00,$08,$0e,$60,$00,$06
Palette_230:
	dc.b	$0e,$80	; $68E2 (blue-high field)
	dc.b	$00,$04,$0e,$a0,$02,$09,$00,$14
	dc.b	$0a,$00,$00,$12,$0c,$00,$00
Palette_231:
	dc.b	$10,$0e	; $68F3 (blue-high field)
	dc.b	$00,$00,$0e,$0e,$20,$00,$0c,$0e
	dc.b	$40,$00,$0a,$0e,$60,$00,$08
Palette_232:
	dc.b	$0e,$80	; $6904 (blue-high field)
	dc.b	$00,$06,$0e,$a0,$00,$04,$0e,$c0
	dc.b	$ff,$00,$30,$38,$8a,$62,$60
Palette_233:
	dc.b	$04,$30	; $6915 (blue-high field)
	dc.b	$38,$8a,$64,$4e,$b8,$05,$a0,$70
	dc.b	$00,$41,$f9,$00,$c0,$00,$00
Palette_234:
	dc.b	$34,$38	; $6926 (blue-high field)
	dc.b	$8a,$72,$36,$38,$8a,$70,$e2,$4b
	dc.b	$32,$03,$20,$80,$53,$41,$66
Palette_235:
	dc.b	$fa,$53	; $6937 (blue-high field)
	dc.b	$42,$66,$f4,$4e,$75,$30,$38,$8a
	dc.b	$66,$4e,$b8,$05,$a0,$70,$00
Palette_236:
	dc.b	$41,$f9	; $6948 (blue-high field)
	dc.b	$00,$c0,$00,$00,$32,$3c,$01,$ff
	dc.b	$20,$80,$51,$c9,$ff,$fc,$11
Palette_237:
	dc.b	$c0,$8a	; $6959 (blue-high field)
	dc.b	$75,$11,$c0,$8a,$77,$31,$c0,$8a
	dc.b	$e4,$00,$38,$00,$04,$80,$06
Palette_238:
	dc.b	$4e,$75	; $696A (blue-high field)
	dc.b	$70,$00,$31,$c0,$8a,$dc,$31,$c0
	dc.b	$8a,$de,$31,$c0,$8a,$e0,$31
Palette_239:
	dc.b	$c0,$8a	; $697B (blue-high field)
	dc.b	$e2,$41,$f9,$00,$ff,$24,$00,$43
	dc.b	$f9,$00,$ff,$26,$00,$32,$3c
Palette_240:
	dc.b	$00,$7f	; $698C (blue-high field)
	dc.b	$61,$0e,$41,$f9,$ff,$ff,$8a,$8c
	dc.b	$43,$f9,$ff,$ff,$8a,$b4,$72
Palette_241:
	dc.b	$09,$20	; $699D (blue-high field)
	dc.b	$c0,$22,$c0,$51,$c9,$ff,$fa,$00
	dc.b	$38,$00,$08,$80,$06,$4e,$75
Palette_242:
	dc.b	$4e,$56	; $69AE (blue-high field)
	dc.b	$ff,$ee,$61,$00,$00,$3e,$7e,$00
	dc.b	$1e,$1a,$0c,$07,$00,$0c,$63
Palette_243:
	dc.b	$06,$61	; $69BF (blue-high field)
	dc.b	$00,$01,$a2,$60,$f2,$70,$00,$10
	dc.b	$07,$d0,$40,$41,$fa,$00,$0a
Palette_244:
	dc.b	$d0,$f0	; $69D0 (blue-high field)
	dc.b	$00,$00,$4e,$90,$60,$e0,$00,$82
	dc.b	$00,$86,$00,$ce,$00,$d4,$00
Palette_245:
	dc.b	$e4,$00	; $69E1 (blue-high field)
	dc.b	$f0,$01,$14,$01,$2e,$01,$36,$01
	dc.b	$38,$01,$44,$01,$58,$01,$5a
Palette_246:
	dc.b	$70,$00	; $69F2 (blue-high field)
	dc.b	$3d,$40,$ff,$f0,$3d,$40,$ff,$ee
	dc.b	$4a,$38,$8c,$76,$6a,$08,$3d
Palette_247:
	dc.b	$78,$8a	; $6A03 (blue-high field)
	dc.b	$66,$ff,$f2,$4e,$75,$30,$38,$8a
	dc.b	$62,$32,$39,$00,$ff,$24,$00
Palette_248:
	dc.b	$34,$39	; $6A14 (blue-high field)
	dc.b	$ff,$ff,$8a,$8c,$08,$38,$00,$00
	dc.b	$8c,$76,$67,$10,$30,$38,$8a
Palette_249:
	dc.b	$64,$32	; $6A25 (blue-high field)
	dc.b	$39,$00,$ff,$26,$00,$34,$39,$ff
	dc.b	$ff,$8a,$b4,$3d,$40,$ff,$f2
Palette_250:
	dc.b	$08,$38	; $6A36 (blue-high field)
	dc.b	$00,$01,$8c,$76,$67,$1a,$44,$41
	dc.b	$58,$41,$c2,$78,$8a,$88,$e6
Palette_251:
	dc.b	$49,$58	; $6A47 (blue-high field)
	dc.b	$42,$c4,$78,$8a,$86,$e6,$4a,$3d
	dc.b	$41,$ff,$f0,$3d,$42,$ff,$ee